apiVersion: v1
kind: ConfigMap
metadata:
  name: apiserver
data:
  JAEGER_ENDPOINT: http://jaeger:14268/api/traces
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_SAMPLER_TYPE: const
  POWERSSL_CA_FILE: /etc/powerssl/ca.pem
  POWERSSL_COMMON_NAME: apiserver
  POWERSSL_CONTROLLER_ADDR: controller:8080
  POWERSSL_CONTROLLER_AUTH_TOKEN: http://auth:8080/service
  POWERSSL_DB_CONNECTION: host=powerssl-postgresql user=powerssl password=powerssl dbname=powerssl sslmode=disable
  POWERSSL_DB_DIALECT: postgres
  POWERSSL_JWKS_URL: http://auth:8080/.well-known/jwks.json
  POWERSSL_VAULT_TOKEN: powerssl-apiserver
  POWERSSL_VAULT_URL: https://vault:8200/
