apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
data:
  JAEGER_ENDPOINT: http://jaeger:14268/api/traces
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_SAMPLER_TYPE: const
  POWERSSL_JWT_PRIVATE_KEY_FILE: /etc/powerssl/auth/signing-key.pem
  POWERSSL_WEBAPP_URI: https://app.test.powerssl.io
