apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-acme
data:
  JAEGER_ENDPOINT: http://jaeger:14268/api/traces
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_SAMPLER_TYPE: const
  POWERSSL_ADDR: controller:8080
  POWERSSL_CA_FILE: /etc/powerssl/ca.pem
