apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  VAULT_LOCAL_CONFIG: '{"listener": {"tcp": {"address": "0.0.0.0:8200", "tls_cert_file": "/etc/certs/vault.crt", "tls_key_file": "/etc/certs/vault.key"}}, "storage": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "api_addr": "https://vault:8200", "cluster_addr": "https://vault:8201", "ui": "true"}'
