apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp
data:
  JAEGER_ENDPOINT: http://jaeger:14268/api/traces
  JAEGER_REPORTER_LOG_SPANS: "true"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_SAMPLER_TYPE: const
  POWERSSL_AUTH_URI: https://auth.test.powerssl.io
