addr: localhost:8083
auth-token: http://localhost:8081/service
metrics-addr: localhost:9093
apiserver:
  addr: localhost:8082
ca-file: local/certs/ca.pem
common-name: localhost
jwks-url: http://localhost:8081/.well-known/jwks.json
vault:
  url: https://localhost:8200
  token: powerssl-controller
