version: "3"
services:
  apiserver:
    depends_on:
      - postgres
    environment:
      POWERSSL_CONTROLLER_ADDR: controller:8080
      POWERSSL_CONTROLLER_AUTH_TOKEN: TODO
      POWERSSL_CONTROLLER_CA_FILE: /etc/powerssl/ca.pem
      POWERSSL_CONTROLLER_INSECURE_SKIP_TLS_VERIFY: "true"
      POWERSSL_DB_CONNECTION: host=postgres user=postgres dbname=postgres sslmode=disable
      POWERSSL_DB_DIALECT: postgres
      POWERSSL_JWT_PUBLIC_KEY_FILE: /etc/powerssl/api/cert.pem
      POWERSSL_TLS_CERT_FILE: /etc/powerssl/api/cert.pem
      POWERSSL_TLS_PRIVATE_KEY_FILE: /etc/powerssl/api/cert-key.pem
    image: powerssl/apiserver:latest
    ports:
      - "8080:8080"
      - "9090"
    volumes:
      - "./examples/certs/ca.pem:/etc/powerssl/ca.pem:ro"
      - "./examples/certs/localhost.pem:/etc/powerssl/api/cert.pem:ro"
      - "./examples/certs/localhost-key.pem:/etc/powerssl/api/cert-key.pem:ro"
  auth:
    environment:
      POWERSSL_JWT_PRIVATE_KEY_FILE: /etc/powerssl/auth/cert-key.pem
      POWERSSL_TLS_CERT_FILE: /etc/powerssl/auth/cert.pem
      POWERSSL_TLS_PRIVATE_KEY_FILE: /etc/powerssl/auth/cert-key.pem
    image: powerssl/auth:latest
    ports:
      - "8081:8080"
      - "9090"
    volumes:
      - "./examples/certs/ca.pem:/etc/powerssl/ca.pem:ro"
      - "./examples/certs/localhost.pem:/etc/powerssl/auth/cert.pem:ro"
      - "./examples/certs/localhost-key.pem:/etc/powerssl/auth/cert-key.pem:ro"
  controller:
    environment:
      POWERSSL_APISERVER_ADDR: apiserver:8080
      POWERSSL_APISERVER_AUTH_TOKEN: TODO
      POWERSSL_APISERVER_CA_FILE: /etc/powerssl/ca.pem
      POWERSSL_APISERVER_INSECURE_SKIP_TLS_VERIFY: "true"
      POWERSSL_JWT_PUBLIC_KEY_FILE: /etc/powerssl/controller/cert.pem
      POWERSSL_TLS_CERT_FILE: /etc/powerssl/controller/cert.pem
      POWERSSL_TLS_PRIVATE_KEY_FILE: /etc/powerssl/controller/cert-key.pem
    image: powerssl/controller:latest
    ports:
      - "8080"
      - "9090"
    volumes:
      - "./examples/certs/ca.pem:/etc/powerssl/ca.pem:ro"
      - "./examples/certs/localhost.pem:/etc/powerssl/controller/cert.pem:ro"
      - "./examples/certs/localhost-key.pem:/etc/powerssl/controller/cert-key.pem:ro"
  integration-acme:
    environment:
      POWERSSL_ADDR: controller:8080
      POWERSSL_CA_FILE: /etc/powerssl/ca.pem
      POWERSSL_INSECURE_SKIP_TLS_VERIFY: "true"
    image: powerssl/integration-acme:latest
    ports:
      - "9090"
    volumes:
      - "./examples/certs/ca.pem:/etc/powerssl/ca.pem:ro"
  signer:
    environment:
      POWERSSL_TLS_CERT_FILE: /etc/powerssl/signer/cert.pem
      POWERSSL_TLS_PRIVATE_KEY_FILE: /etc/powerssl/signer/cert-key.pem
    image: powerssl/signer:latest
    ports:
      - "8080"
      - "9090"
    volumes:
      - "./examples/certs/ca.pem:/etc/powerssl/ca.pem:ro"
      - "./examples/certs/localhost.pem:/etc/powerssl/signer/cert.pem:ro"
      - "./examples/certs/localhost-key.pem:/etc/powerssl/signer/cert-key.pem:ro"
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
# jaeger:
#   environment:
#     COLLECTOR_ZIPKIN_HTTP_PORT: 9411
#   image: jaegertracing/all-in-one:1.7
#   ports:
#     - "5775/udp"
#     - "6831/udp"
#     - "6832/udp"
#     - "5778"
#     - "16686"
#     - "14268"
#     - "9411"
volumes:
  postgres-data:
