version: "3"
services:
  apiserver:
    depends_on:
      - postgres
      - vault
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SAMPLER_TYPE: const
      POWERSSL_CA_FILE: /etc/powerssl/ca.pem
      POWERSSL_COMMON_NAME: apiserver
      POWERSSL_CONTROLLER_ADDR: controller:8080
      POWERSSL_CONTROLLER_AUTH_TOKEN: http://auth:8080/service
      POWERSSL_DB_CONNECTION: host=postgres user=postgres dbname=postgres sslmode=disable
      POWERSSL_DB_DIALECT: postgres
      POWERSSL_JWKS_URL: http://auth:8080/.well-known/jwks.json
      POWERSSL_VAULT_TOKEN: powerssl-apiserver
      POWERSSL_VAULT_URL: https://vault:8200/
    image: powerssl/apiserver:latest
    ports:
      - "8443:8080"
      - "9090"
    restart: always
    volumes:
      - "./local/certs/ca.pem:/etc/powerssl/ca.pem:ro"
  auth:
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SAMPLER_TYPE: const
      POWERSSL_JWT_PRIVATE_KEY_FILE: /etc/powerssl/auth/cert-key.pem
      POWERSSL_WEBAPP_URI: http://localhost:8080
    image: powerssl/auth:latest
    ports:
      - "8081:8080"
      - "9090"
    restart: always
    volumes:
      - "./local/certs/localhost-key.pem:/etc/powerssl/auth/cert-key.pem:ro"
  controller:
    depends_on:
      - vault
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SAMPLER_TYPE: const
      POWERSSL_CA_FILE: /etc/powerssl/ca.pem
      POWERSSL_COMMON_NAME: controller
      POWERSSL_APISERVER_ADDR: apiserver:8080
      POWERSSL_APISERVER_AUTH_TOKEN: http://auth:8080/service
      POWERSSL_JWKS_URL: http://auth:8080/.well-known/jwks.json
      POWERSSL_VAULT_TOKEN: powerssl-controller
      POWERSSL_VAULT_URL: https://vault:8200/
    image: powerssl/controller:latest
    ports:
      - "8080"
      - "9090"
    restart: always
    volumes:
      - "./local/certs/ca.pem:/etc/powerssl/ca.pem:ro"
  integration-acme:
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SAMPLER_TYPE: const
      POWERSSL_ADDR: controller:8080
      POWERSSL_CA_FILE: /etc/powerssl/ca.pem
    image: powerssl/integration-acme:latest
    ports:
      - "9090"
    restart: always
    volumes:
      - "./local/certs/ca.pem:/etc/powerssl/ca.pem:ro"
  signer:
    depends_on:
      - vault
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SAMPLER_TYPE: const
      POWERSSL_CA_FILE: /etc/powerssl/ca.pem
      POWERSSL_COMMON_NAME: signer
      POWERSSL_VAULT_TOKEN: powerssl-signer
      POWERSSL_VAULT_URL: https://vault:8200/
    image: powerssl/signer:latest
    ports:
      - "8080"
      - "9090"
    restart: always
    volumes:
      - "./local/certs/ca.pem:/etc/powerssl/ca.pem:ro"
  webapp:
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SAMPLER_TYPE: const
      POWERSSL_AUTH_URI: http://localhost:8081
    image: powerssl/webapp:latest
    ports:
      - "8080:8080"
      - "9090"
    restart: always
    volumes:
      - "./local/certs/ca.pem:/etc/powerssl/ca.pem:ro"
  postgres:
    image: postgres:11.1-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  vault:
    command: ["server"]
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: '{"listener": {"tcp": {"address": "0.0.0.0:8200", "tls_cert_file": "/etc/certs/vault.crt", "tls_key_file": "/etc/certs/vault.key"}}, "storage": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "api_addr": "https://vault:8200", "cluster_addr": "https://vault:8201", "ui": "true"}'
    image: vault:1.0.2
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./local/certs/vault-key.pem:/etc/certs/vault.key:ro
      - ./local/certs/vault.pem:/etc/certs/vault.crt:ro
      - vault-data:/vault/file
  jaeger:
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    image: jaegertracing/all-in-one:1.8
    restart: always
    ports:
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
      - "5778"
      - "16686:16686"
      - "14268"
      - "9411"
volumes:
  postgres-data:
  vault-data:
