powerctl:
- cmd/powerctl/*
- internal/app/powerctl/**/*

powerssl-agent:
- cmd/powerssl-agent/*
- internal/app/agent/**/*

powerssl-apiserver:
- cmd/powerssl-apiserver/*
- internal/app/apiserver/**/*
- pkg/apiserver/**/*

powerssl-auth:
- cmd/powerssl-auth/*
- internal/app/auth/**/*

powerssl-controller:
- cmd/powerssl-controller/*
- internal/app/controller/**/*
- pkg/controller/**/*

powerssl-grpcgateway:
- cmd/powerssl-grpcgateway/*
- internal/app/grpcgateway/**/*

powerssl-integration-acme:
- cmd/powerssl-integration-acme/*
- internal/app/integrations/acme/**/*
- pkg/integration/**/*

powerssl-integration-cloudflare:
- cmd/powerssl-integration-cloudflare/*
- internal/app/integrations/cloudflare/**/*
- pkg/integration/**/*

powerssl-signer:
- cmd/powerssl-signer/*
- internal/app/signer/**/*

powerssl-webapp:
- cmd/powerssl-webapp/*
- internal/app/webapp/**/*

powerutil:
- cmd/powerutil/*
- internal/app/powerutil/**/*
