image: golang:1.11

stages:
    - test
    - build

format:
    stage: test
    script:
      - make fmt
      - make vet

compile:
    stage: build
    script:
      - make build
    artifacts:
      paths:
        - bin/powerssl-api
        - bin/powerctl
