image: golang:1.11

variables:
  GO111MODULE: "on"

stages:
    - build

build:
    stage: build
    script:
      - make build
    artifacts:
      paths:
        - bin/powerssl-api
        - bin/powerctl
