image: golang:1.11

variables:
  GOPATH: "$CI_PROJECT_DIR/go"

stages:
    - build

build:
    artifacts:
      name: "$CI_COMMIT_REF_NAME"
      paths:
        - bin/powerctl
        - bin/powerssl-apiserver
    cache:
      key: "$CI_COMMIT_REF_SLUG"
      paths:
        - "go/pkg/mod"
    dependencies: []
    script:
      - make build
    stage: build
