db:
  connString: postgresql://powerssl:powerssl@localhost:5432/powerssl?sslmode=disable
log:
  env: development
server:
  addr: localhost:8082
  certFile:
  commonName: localhost
  insecure: false
  keyFile:
  vault:
    appRoleID:
    appRoleSecretID:
    caFile: local/certs/ca.pem
    token:
    url: https://localhost:8200
temporalClient:
  caFile: local/certs/ca.pem
  disableHealthCheck:
  healthCheckTimeout:
  hostPort: localhost:7233
  identity:
  namespace: powerssl
  tlsCertFile:
  tlsKeyFile:
telemetry:
  meter:
    addr: localhost:9092
    exporter: prometheus
  tracer:
    exporter: jaeger
