db:
  connString: postgresql://powerssl:powerssl@localhost:5432/powerssl?sslmode=disable
log:
  env: development
metrics:
  addr: localhost:9092
server:
  addr: localhost:8082
  caFile: local/certs/ca.pem
  certFile:
  commonName: localhost
  insecure: false
  keyFile:
  vaultRole:
  vaultToken:
  vaultURL: https://localhost:8200
temporalClient:
  caFile: local/certs/ca.pem
  disableHealthCheck:
  healthCheckTimeout:
  hostPort: localhost:7233
  identity:
  namespace: powerssl
  tlsCertFile:
  tlsKeyFile:
tracer:
  implementation: jaeger
