// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	"powerssl.dev/common/interrupthandler"
	"powerssl.dev/common/log"
	"powerssl.dev/common/metrics"
	"powerssl.dev/webapp/internal/server"
)

// Injectors from wire.go:

func Initialize(ctx context.Context, cfg *Config) ([]func() error, func(), error) {
	sugaredLogger, cleanup, err := log.ProvideLogger()
	if err != nil {
		return nil, nil, err
	}
	f := interrupthandler.Provide(ctx, sugaredLogger)
	config := &cfg.Metrics
	metricsF := metrics.Provide(ctx, config, sugaredLogger)
	serverConfig := &cfg.Server
	serverF := server.Provide(ctx, serverConfig, sugaredLogger)
	v := provideRunnerF(f, metricsF, serverF)
	return v, func() {
		cleanup()
	}, nil
}
