// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	"powerssl.dev/apiserver/internal/repository"
	"powerssl.dev/apiserver/internal/service"
	"powerssl.dev/apiserver/internal/service/acmeaccount"
	"powerssl.dev/apiserver/internal/service/acmeserver"
	"powerssl.dev/apiserver/internal/service/certificate"
	"powerssl.dev/apiserver/internal/service/user"
	"powerssl.dev/backend/grpcserver"
	"powerssl.dev/backend/temporal/client"
	"powerssl.dev/common/interrupthandler"
	"powerssl.dev/common/log"
	"powerssl.dev/common/telemetry"
)

// Injectors from wire.go:

func Initialize(ctx context.Context, cfg *Config) ([]func() error, func(), error) {
	config := cfg.Log
	logger, cleanup, err := log.Provide(config)
	if err != nil {
		return nil, nil, err
	}
	f := interrupthandler.Provide(ctx, logger)
	grpcserverConfig := cfg.Server
	repositoryConfig := cfg.DB
	dbtx, cleanup2, err := repository.Provide(ctx, repositoryConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	queries := repository.New(dbtx)
	telemetryConfig := cfg.Telemetry
	telemeter, cleanup3, err := telemetry.Provide(ctx, telemetryConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	clientConfig := cfg.TemporalClient
	clientClient, err := client.Provide(clientConfig, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	acmeaccountService := acmeaccount.New(logger, queries, telemeter, clientClient)
	acmeserverService := acmeserver.New(logger, queries, telemeter)
	certificateService := certificate.New(logger, queries, telemeter)
	userService := user.New(logger, queries, telemeter)
	register := service.Provide(acmeaccountService, acmeserverService, certificateService, userService)
	grpcserverF, err := grpcserver.Provide(ctx, grpcserverConfig, logger, register)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	telemetryF := telemetry.ProvideF(ctx, telemeter)
	v := Provide(f, grpcserverF, telemetryF)
	return v, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
