addr: localhost:8843
jwt:
  private-key-file: local/certs/ca-key.pem
insecure: false
metrics:
  addr: localhost:9091
tls:
  cert-file: local/certs/localhost.pem
  private-key-file: local/certs/localhost-key.pem
webapp:
  uri: https://localhost:8443
