log:
  env: development
server:
  addr: localhost:8843
  insecure: false
  certFile: local/certs/localhost.pem
  keyFile: local/certs/localhost-key.pem
  jwtPrivateKeyFile: local/certs/ca-key.pem
  webappURI: https://localhost:8443
oauth2:
  authURI: https://localhost:8843
  github:
    clientID: da92ab4fd752a1e5dc1a
    clientSecret: 5b2a050592c3add5da9903fc3b975b160f5f8924
telemetry:
  meter:
    addr: localhost:9091
    exporter: prometheus
  tracer:
    exporter: jaeger
