addr: localhost:8085
apiserver:
  addr: localhost:8082
  ca-file:
  insecure: false
  insecure-skip-tls-verify: false
  server-name-override:
ca-file: local/certs/ca.pem
metrics:
  addr: localhost:9095
