apiServerClient:
  addr: localhost:8082
  caFile: local/certs/ca.pem
  insecure: false
  insecureSkipTLSVerify: false
  serverNameOverride:
log:
  env: development
telemetry:
  meter:
    addr: localhost:9095
    exporter: prometheus
  tracer:
    exporter: jaeger
server:
  addr: localhost:8085
