apiServerClient:
  addr: localhost:8082
  caFile: local/certs/ca.pem
  insecure: false
  insecureSkipTLSVerify: false
  serverNameOverride:
log:
  env: development
metrics:
  addr: localhost:9095
server:
  addr: localhost:8085
