// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/certificate.proto

package api // import "powerssl.io/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/gogo/protobuf/types"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateCertificateRequest struct {
	Certificate          *Certificate `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateCertificateRequest) Reset()         { *m = CreateCertificateRequest{} }
func (m *CreateCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCertificateRequest) ProtoMessage()    {}
func (*CreateCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{0}
}
func (m *CreateCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCertificateRequest.Unmarshal(m, b)
}
func (m *CreateCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCertificateRequest.Merge(dst, src)
}
func (m *CreateCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCertificateRequest.Size(m)
}
func (m *CreateCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCertificateRequest proto.InternalMessageInfo

func (m *CreateCertificateRequest) GetCertificate() *Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

type DeleteCertificateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCertificateRequest) Reset()         { *m = DeleteCertificateRequest{} }
func (m *DeleteCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCertificateRequest) ProtoMessage()    {}
func (*DeleteCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{1}
}
func (m *DeleteCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCertificateRequest.Unmarshal(m, b)
}
func (m *DeleteCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCertificateRequest.Merge(dst, src)
}
func (m *DeleteCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCertificateRequest.Size(m)
}
func (m *DeleteCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCertificateRequest proto.InternalMessageInfo

func (m *DeleteCertificateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCertificateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCertificateRequest) Reset()         { *m = GetCertificateRequest{} }
func (m *GetCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*GetCertificateRequest) ProtoMessage()    {}
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{2}
}
func (m *GetCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCertificateRequest.Unmarshal(m, b)
}
func (m *GetCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *GetCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCertificateRequest.Merge(dst, src)
}
func (m *GetCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_GetCertificateRequest.Size(m)
}
func (m *GetCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCertificateRequest proto.InternalMessageInfo

func (m *GetCertificateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListCertificatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCertificatesRequest) Reset()         { *m = ListCertificatesRequest{} }
func (m *ListCertificatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCertificatesRequest) ProtoMessage()    {}
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{3}
}
func (m *ListCertificatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCertificatesRequest.Unmarshal(m, b)
}
func (m *ListCertificatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCertificatesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCertificatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCertificatesRequest.Merge(dst, src)
}
func (m *ListCertificatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCertificatesRequest.Size(m)
}
func (m *ListCertificatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCertificatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCertificatesRequest proto.InternalMessageInfo

type ListCertificatesResponse struct {
	TypeMeta             *TypeMeta      `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta" json:"type_meta,omitempty"`
	ListMeta             *ListMeta      `protobuf:"bytes,2,opt,name=list_meta,json=listMeta" json:"list_meta,omitempty"`
	Items                []*Certificate `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListCertificatesResponse) Reset()         { *m = ListCertificatesResponse{} }
func (m *ListCertificatesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCertificatesResponse) ProtoMessage()    {}
func (*ListCertificatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{4}
}
func (m *ListCertificatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCertificatesResponse.Unmarshal(m, b)
}
func (m *ListCertificatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCertificatesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCertificatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCertificatesResponse.Merge(dst, src)
}
func (m *ListCertificatesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCertificatesResponse.Size(m)
}
func (m *ListCertificatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCertificatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCertificatesResponse proto.InternalMessageInfo

func (m *ListCertificatesResponse) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *ListCertificatesResponse) GetListMeta() *ListMeta {
	if m != nil {
		return m.ListMeta
	}
	return nil
}

func (m *ListCertificatesResponse) GetItems() []*Certificate {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateCertificateRequest struct {
	Certificate          *Certificate `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateCertificateRequest) Reset()         { *m = UpdateCertificateRequest{} }
func (m *UpdateCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCertificateRequest) ProtoMessage()    {}
func (*UpdateCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{5}
}
func (m *UpdateCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCertificateRequest.Unmarshal(m, b)
}
func (m *UpdateCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCertificateRequest.Merge(dst, src)
}
func (m *UpdateCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCertificateRequest.Size(m)
}
func (m *UpdateCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCertificateRequest proto.InternalMessageInfo

func (m *UpdateCertificateRequest) GetCertificate() *Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

type Certificate struct {
	TypeMeta             *TypeMeta          `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta" json:"type_meta,omitempty"`
	ObjectMeta           *ObjectMeta        `protobuf:"bytes,2,opt,name=object_meta,json=objectMeta" json:"object_meta,omitempty"`
	Spec                 *CertificateSpec   `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
	Status               *CertificateStatus `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{6}
}
func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (dst *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(dst, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetTypeMeta() *TypeMeta {
	if m != nil {
		return m.TypeMeta
	}
	return nil
}

func (m *Certificate) GetObjectMeta() *ObjectMeta {
	if m != nil {
		return m.ObjectMeta
	}
	return nil
}

func (m *Certificate) GetSpec() *CertificateSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Certificate) GetStatus() *CertificateStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type CertificateSpec struct {
	CommonName           string   `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	EncryptionAlgorithm  string   `protobuf:"bytes,2,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryption_algorithm,omitempty"`
	KeySize              int32    `protobuf:"varint,3,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	SignatureAlgorithm   string   `protobuf:"bytes,4,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	AutoRenew            bool     `protobuf:"varint,5,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateSpec) Reset()         { *m = CertificateSpec{} }
func (m *CertificateSpec) String() string { return proto.CompactTextString(m) }
func (*CertificateSpec) ProtoMessage()    {}
func (*CertificateSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{7}
}
func (m *CertificateSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateSpec.Unmarshal(m, b)
}
func (m *CertificateSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateSpec.Marshal(b, m, deterministic)
}
func (dst *CertificateSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateSpec.Merge(dst, src)
}
func (m *CertificateSpec) XXX_Size() int {
	return xxx_messageInfo_CertificateSpec.Size(m)
}
func (m *CertificateSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateSpec proto.InternalMessageInfo

func (m *CertificateSpec) GetCommonName() string {
	if m != nil {
		return m.CommonName
	}
	return ""
}

func (m *CertificateSpec) GetEncryptionAlgorithm() string {
	if m != nil {
		return m.EncryptionAlgorithm
	}
	return ""
}

func (m *CertificateSpec) GetKeySize() int32 {
	if m != nil {
		return m.KeySize
	}
	return 0
}

func (m *CertificateSpec) GetSignatureAlgorithm() string {
	if m != nil {
		return m.SignatureAlgorithm
	}
	return ""
}

func (m *CertificateSpec) GetAutoRenew() bool {
	if m != nil {
		return m.AutoRenew
	}
	return false
}

type CertificateStatus struct {
	Phase                string   `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateStatus) Reset()         { *m = CertificateStatus{} }
func (m *CertificateStatus) String() string { return proto.CompactTextString(m) }
func (*CertificateStatus) ProtoMessage()    {}
func (*CertificateStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_eee690f11a99a678, []int{8}
}
func (m *CertificateStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateStatus.Unmarshal(m, b)
}
func (m *CertificateStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateStatus.Marshal(b, m, deterministic)
}
func (dst *CertificateStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateStatus.Merge(dst, src)
}
func (m *CertificateStatus) XXX_Size() int {
	return xxx_messageInfo_CertificateStatus.Size(m)
}
func (m *CertificateStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateStatus proto.InternalMessageInfo

func (m *CertificateStatus) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCertificateRequest)(nil), "powerssl.api.v1.CreateCertificateRequest")
	proto.RegisterType((*DeleteCertificateRequest)(nil), "powerssl.api.v1.DeleteCertificateRequest")
	proto.RegisterType((*GetCertificateRequest)(nil), "powerssl.api.v1.GetCertificateRequest")
	proto.RegisterType((*ListCertificatesRequest)(nil), "powerssl.api.v1.ListCertificatesRequest")
	proto.RegisterType((*ListCertificatesResponse)(nil), "powerssl.api.v1.ListCertificatesResponse")
	proto.RegisterType((*UpdateCertificateRequest)(nil), "powerssl.api.v1.UpdateCertificateRequest")
	proto.RegisterType((*Certificate)(nil), "powerssl.api.v1.Certificate")
	proto.RegisterType((*CertificateSpec)(nil), "powerssl.api.v1.CertificateSpec")
	proto.RegisterType((*CertificateStatus)(nil), "powerssl.api.v1.CertificateStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CertificateService service

type CertificateServiceClient interface {
	Create(ctx context.Context, in *CreateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error)
	Delete(ctx context.Context, in *DeleteCertificateRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Get(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*Certificate, error)
	List(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error)
	Update(ctx context.Context, in *UpdateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error)
}

type certificateServiceClient struct {
	cc *grpc.ClientConn
}

func NewCertificateServiceClient(cc *grpc.ClientConn) CertificateServiceClient {
	return &certificateServiceClient{cc}
}

func (c *certificateServiceClient) Create(ctx context.Context, in *CreateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error) {
	out := new(Certificate)
	err := c.cc.Invoke(ctx, "/powerssl.api.v1.CertificateService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Delete(ctx context.Context, in *DeleteCertificateRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/powerssl.api.v1.CertificateService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Get(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*Certificate, error) {
	out := new(Certificate)
	err := c.cc.Invoke(ctx, "/powerssl.api.v1.CertificateService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) List(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error) {
	out := new(ListCertificatesResponse)
	err := c.cc.Invoke(ctx, "/powerssl.api.v1.CertificateService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Update(ctx context.Context, in *UpdateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error) {
	out := new(Certificate)
	err := c.cc.Invoke(ctx, "/powerssl.api.v1.CertificateService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CertificateService service

type CertificateServiceServer interface {
	Create(context.Context, *CreateCertificateRequest) (*Certificate, error)
	Delete(context.Context, *DeleteCertificateRequest) (*types.Empty, error)
	Get(context.Context, *GetCertificateRequest) (*Certificate, error)
	List(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error)
	Update(context.Context, *UpdateCertificateRequest) (*Certificate, error)
}

func RegisterCertificateServiceServer(s *grpc.Server, srv CertificateServiceServer) {
	s.RegisterService(&_CertificateService_serviceDesc, srv)
}

func _CertificateService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.api.v1.CertificateService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Create(ctx, req.(*CreateCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.api.v1.CertificateService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Delete(ctx, req.(*DeleteCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.api.v1.CertificateService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Get(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.api.v1.CertificateService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).List(ctx, req.(*ListCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.api.v1.CertificateService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Update(ctx, req.(*UpdateCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertificateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "powerssl.api.v1.CertificateService",
	HandlerType: (*CertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CertificateService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CertificateService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CertificateService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CertificateService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CertificateService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/certificate.proto",
}

func init() {
	proto.RegisterFile("api/v1/certificate.proto", fileDescriptor_certificate_eee690f11a99a678)
}

var fileDescriptor_certificate_eee690f11a99a678 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xad, 0x7f, 0xf9, 0xf3, 0x6b, 0x26, 0x87, 0xaa, 0xdb, 0x02, 0xae, 0x5b, 0x44, 0xe4, 0x03,
	0x6a, 0x85, 0x64, 0xab, 0x05, 0x71, 0x00, 0x84, 0x04, 0x05, 0xf5, 0x42, 0x41, 0x72, 0xe1, 0x52,
	0x09, 0x45, 0x1b, 0x33, 0x4d, 0x97, 0xd8, 0xde, 0xc5, 0xbb, 0x49, 0xe5, 0x7e, 0x35, 0x24, 0x3e,
	0x03, 0x5f, 0x86, 0x3b, 0xf2, 0xae, 0x93, 0x98, 0xda, 0x49, 0x2a, 0x24, 0x6e, 0xe3, 0x99, 0xf7,
	0xde, 0xee, 0x8c, 0x77, 0x1e, 0xd8, 0x54, 0x30, 0x7f, 0x72, 0xe8, 0x87, 0x98, 0x2a, 0x76, 0xc1,
	0x42, 0xaa, 0xd0, 0x13, 0x29, 0x57, 0x9c, 0x6c, 0x08, 0x7e, 0x85, 0xa9, 0x94, 0x91, 0x47, 0x05,
	0xf3, 0x26, 0x87, 0xce, 0xee, 0x90, 0xf3, 0x61, 0x84, 0xbe, 0x2e, 0x0f, 0xc6, 0x17, 0x3e, 0xc6,
	0x42, 0x65, 0x06, 0xed, 0x6c, 0x16, 0x3a, 0x31, 0x2a, 0x6a, 0x52, 0xee, 0x39, 0xd8, 0xc7, 0x29,
	0x52, 0x85, 0xc7, 0x73, 0xed, 0x00, 0xbf, 0x8d, 0x51, 0x2a, 0xf2, 0x12, 0xba, 0xa5, 0x13, 0x6d,
	0xab, 0x67, 0xed, 0x77, 0x8f, 0xf6, 0xbc, 0x1b, 0x47, 0x7a, 0x65, 0x66, 0x99, 0xe0, 0x7a, 0x60,
	0xbf, 0xc1, 0x08, 0x6b, 0xb5, 0x09, 0x34, 0x13, 0x1a, 0x1b, 0xd1, 0x4e, 0xa0, 0x63, 0xf7, 0x11,
	0xdc, 0x39, 0x41, 0x75, 0x4b, 0xf0, 0x0e, 0xdc, 0x7b, 0xc7, 0x64, 0x19, 0x2d, 0x0b, 0xb8, 0xfb,
	0xc3, 0x02, 0xbb, 0x5a, 0x93, 0x82, 0x27, 0x12, 0xc9, 0x53, 0xe8, 0xa8, 0x4c, 0x60, 0x3f, 0x9f,
	0x41, 0xd1, 0xd2, 0x4e, 0xa5, 0xa5, 0x8f, 0x99, 0xc0, 0x53, 0x54, 0x34, 0x58, 0x57, 0x45, 0x94,
	0xf3, 0x22, 0x26, 0x95, 0xe1, 0xfd, 0xb7, 0x80, 0x97, 0x9f, 0x6a, 0x78, 0x51, 0x11, 0x91, 0x23,
	0x68, 0x31, 0x85, 0xb1, 0xb4, 0x1b, 0xbd, 0xc6, 0xca, 0xf1, 0x19, 0x68, 0xfe, 0x53, 0x3e, 0x89,
	0x2f, 0xff, 0xe6, 0xa7, 0xfc, 0xb2, 0xa0, 0x5b, 0x2a, 0xfe, 0xf5, 0x3c, 0x5e, 0x40, 0x97, 0x0f,
	0xbe, 0x62, 0xf8, 0xc7, 0x44, 0x76, 0x2b, 0xcc, 0x0f, 0x1a, 0xa3, 0xb9, 0xc0, 0x67, 0x31, 0x79,
	0x02, 0x4d, 0x29, 0x30, 0xb4, 0x1b, 0x9a, 0xd6, 0x5b, 0x76, 0xfd, 0x33, 0x81, 0x61, 0xa0, 0xd1,
	0xe4, 0x19, 0xb4, 0xa5, 0xa2, 0x6a, 0x2c, 0xed, 0xa6, 0xe6, 0xb9, 0x4b, 0x79, 0x1a, 0x19, 0x14,
	0x0c, 0xf7, 0xa7, 0x05, 0x1b, 0x37, 0x54, 0xc9, 0x03, 0xe8, 0x86, 0x3c, 0x8e, 0x79, 0xd2, 0x2f,
	0x3d, 0x2f, 0x30, 0xa9, 0xf7, 0x34, 0x46, 0x72, 0x08, 0xdb, 0x98, 0x84, 0x69, 0x26, 0x14, 0xe3,
	0x49, 0x9f, 0x46, 0x43, 0x9e, 0x32, 0x75, 0x19, 0xeb, 0x6e, 0x3b, 0xc1, 0xd6, 0xbc, 0xf6, 0x6a,
	0x5a, 0x22, 0x3b, 0xb0, 0x3e, 0xc2, 0xac, 0x2f, 0xd9, 0x35, 0xea, 0xee, 0x5a, 0xc1, 0xff, 0x23,
	0xcc, 0xce, 0xd8, 0x35, 0x12, 0x1f, 0xb6, 0x24, 0x1b, 0x26, 0x54, 0x8d, 0x53, 0x2c, 0x89, 0x35,
	0xb5, 0x18, 0x99, 0x95, 0xe6, 0x5a, 0xf7, 0x01, 0xe8, 0x58, 0xf1, 0x7e, 0x8a, 0x09, 0x5e, 0xd9,
	0xad, 0x9e, 0xb5, 0xbf, 0x1e, 0x74, 0xf2, 0x4c, 0x90, 0x27, 0xdc, 0x03, 0xd8, 0xac, 0xf4, 0x4b,
	0xb6, 0xa1, 0x25, 0x2e, 0xa9, 0x9c, 0x76, 0x63, 0x3e, 0x8e, 0xbe, 0x37, 0x80, 0x94, 0xb1, 0x98,
	0x4e, 0x58, 0x88, 0xe4, 0x0c, 0xda, 0x66, 0xfb, 0xc9, 0x41, 0x75, 0x94, 0x0b, 0x6c, 0xc1, 0x59,
	0xfa, 0xd8, 0xdc, 0x35, 0x72, 0x0a, 0x6d, 0xb3, 0xf6, 0x35, 0xa2, 0x8b, 0xfc, 0xc0, 0xb9, 0xeb,
	0x19, 0xe3, 0xf2, 0xa6, 0xc6, 0xe5, 0xbd, 0xcd, 0x8d, 0x4b, 0xcb, 0x35, 0x4e, 0x50, 0x91, 0x87,
	0x15, 0xad, 0x5a, 0xaf, 0x58, 0x79, 0xbb, 0xcf, 0xd0, 0xcc, 0xb7, 0x94, 0xec, 0xd7, 0x2e, 0x6f,
	0x8d, 0x9d, 0x38, 0x07, 0xb7, 0x40, 0x1a, 0x73, 0x71, 0xd7, 0xf2, 0x89, 0x9a, 0xd5, 0xad, 0x69,
	0x7e, 0xd1, 0x4e, 0xaf, 0xba, 0xf3, 0xeb, 0xbd, 0x73, 0x67, 0x06, 0x60, 0xdc, 0x17, 0xa3, 0xa1,
	0x6f, 0x9c, 0xfc, 0x39, 0x15, 0x6c, 0xd0, 0xd6, 0x23, 0x7b, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x22, 0x92, 0xb2, 0x48, 0x26, 0x06, 0x00, 0x00,
}
