// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	"powerssl.dev/backend/temporal/client"
	"powerssl.dev/backend/grpcserver"
	"powerssl.dev/backend/vault"
	"powerssl.dev/common/interrupthandler"
	"powerssl.dev/common/log"
	"powerssl.dev/common/metrics"
	"powerssl.dev/common/tracer"
	"powerssl.dev/controller/internal/service"
	"powerssl.dev/controller/internal/service/acme"
	"powerssl.dev/controller/internal/service/integration"
	"powerssl.dev/controller/internal/worker"
	"powerssl.dev/sdk/apiserver"
)

// Injectors from wire.go:

func Initialize(ctx context.Context, cfg *Config) ([]func() error, func(), error) {
	config := cfg.Log
	sugaredLogger, cleanup, err := log.Provide(config)
	if err != nil {
		return nil, nil, err
	}
	f := interrupthandler.Provide(ctx, sugaredLogger)
	metricsConfig := cfg.Metrics
	metricsF := metrics.Provide(ctx, metricsConfig, sugaredLogger)
	serverConfig := cfg.Server
	clientConfig := cfg.TemporalClient
	tracerConfig := cfg.Tracer
	opentracingTracer, cleanup2, err := tracer.Provide(tracerConfig, sugaredLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clientClient, cleanup3, err := client.Provide(clientConfig, sugaredLogger, opentracingTracer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	acmeService := acme.New(sugaredLogger, clientClient)
	integrationService := integration.New(ctx, sugaredLogger)
	register := service.Provide(acmeService, integrationService)
	transportF, err := grpcserver.Provide(ctx, serverConfig, sugaredLogger, register)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	apiserverConfig := cfg.APIServerClient
	apiserverClient, err := apiserver.NewClient(ctx, apiserverConfig, sugaredLogger, opentracingTracer)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	vaultClientConfig := cfg.VaultClient
	vaultClient, err := vault.New(vaultClientConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workerF := worker.Provide(ctx, apiserverClient, vaultClient, clientClient)
	v := Provide(f, metricsF, transportF, workerF)
	return v, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
