// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.3
// source: powerssl/controller/v1/integration.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IntegrationKind int32

const (
	IntegrationKind_INTEGRATION_KIND_UNSPECIFIED IntegrationKind = 0
	IntegrationKind_ACME                         IntegrationKind = 1
	IntegrationKind_DNS                          IntegrationKind = 2
)

// Enum value maps for IntegrationKind.
var (
	IntegrationKind_name = map[int32]string{
		0: "INTEGRATION_KIND_UNSPECIFIED",
		1: "ACME",
		2: "DNS",
	}
	IntegrationKind_value = map[string]int32{
		"INTEGRATION_KIND_UNSPECIFIED": 0,
		"ACME":                         1,
		"DNS":                          2,
	}
)

func (x IntegrationKind) Enum() *IntegrationKind {
	p := new(IntegrationKind)
	*p = x
	return p
}

func (x IntegrationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_powerssl_controller_v1_integration_proto_enumTypes[0].Descriptor()
}

func (IntegrationKind) Type() protoreflect.EnumType {
	return &file_powerssl_controller_v1_integration_proto_enumTypes[0]
}

func (x IntegrationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationKind.Descriptor instead.
func (IntegrationKind) EnumDescriptor() ([]byte, []int) {
	return file_powerssl_controller_v1_integration_proto_rawDescGZIP(), []int{0}
}

type RegisterIntegrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind IntegrationKind `protobuf:"varint,1,opt,name=kind,proto3,enum=powerssl.controller.v1.IntegrationKind" json:"kind,omitempty"`
	Name string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RegisterIntegrationRequest) Reset() {
	*x = RegisterIntegrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerssl_controller_v1_integration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIntegrationRequest) ProtoMessage() {}

func (x *RegisterIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_powerssl_controller_v1_integration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIntegrationRequest.ProtoReflect.Descriptor instead.
func (*RegisterIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_powerssl_controller_v1_integration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterIntegrationRequest) GetKind() IntegrationKind {
	if x != nil {
		return x.Kind
	}
	return IntegrationKind_INTEGRATION_KIND_UNSPECIFIED
}

func (x *RegisterIntegrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_powerssl_controller_v1_integration_proto protoreflect.FileDescriptor

var file_powerssl_controller_v1_integration_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x73, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x73, 0x73, 0x6c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x1a, 0x21, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x73, 0x6c, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x27, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x73, 0x6c, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x2a, 0x46, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x1c, 0x49, 0x4e, 0x54, 0x45, 0x47,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x43, 0x4d,
	0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x4e, 0x53, 0x10, 0x02, 0x32, 0x7a, 0x0a, 0x12,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x64, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x32,
	0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x73, 0x6c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x73, 0x6c, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x22, 0x00, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x73, 0x73, 0x6c, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_powerssl_controller_v1_integration_proto_rawDescOnce sync.Once
	file_powerssl_controller_v1_integration_proto_rawDescData = file_powerssl_controller_v1_integration_proto_rawDesc
)

func file_powerssl_controller_v1_integration_proto_rawDescGZIP() []byte {
	file_powerssl_controller_v1_integration_proto_rawDescOnce.Do(func() {
		file_powerssl_controller_v1_integration_proto_rawDescData = protoimpl.X.CompressGZIP(file_powerssl_controller_v1_integration_proto_rawDescData)
	})
	return file_powerssl_controller_v1_integration_proto_rawDescData
}

var file_powerssl_controller_v1_integration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_powerssl_controller_v1_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_powerssl_controller_v1_integration_proto_goTypes = []interface{}{
	(IntegrationKind)(0),               // 0: powerssl.controller.v1.IntegrationKind
	(*RegisterIntegrationRequest)(nil), // 1: powerssl.controller.v1.RegisterIntegrationRequest
	(*Activity)(nil),                   // 2: powerssl.controller.v1.Activity
}
var file_powerssl_controller_v1_integration_proto_depIdxs = []int32{
	0, // 0: powerssl.controller.v1.RegisterIntegrationRequest.kind:type_name -> powerssl.controller.v1.IntegrationKind
	1, // 1: powerssl.controller.v1.IntegrationService.Register:input_type -> powerssl.controller.v1.RegisterIntegrationRequest
	2, // 2: powerssl.controller.v1.IntegrationService.Register:output_type -> powerssl.controller.v1.Activity
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_powerssl_controller_v1_integration_proto_init() }
func file_powerssl_controller_v1_integration_proto_init() {
	if File_powerssl_controller_v1_integration_proto != nil {
		return
	}
	file_powerssl_controller_v1_meta_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_powerssl_controller_v1_integration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterIntegrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_powerssl_controller_v1_integration_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_powerssl_controller_v1_integration_proto_goTypes,
		DependencyIndexes: file_powerssl_controller_v1_integration_proto_depIdxs,
		EnumInfos:         file_powerssl_controller_v1_integration_proto_enumTypes,
		MessageInfos:      file_powerssl_controller_v1_integration_proto_msgTypes,
	}.Build()
	File_powerssl_controller_v1_integration_proto = out.File
	file_powerssl_controller_v1_integration_proto_rawDesc = nil
	file_powerssl_controller_v1_integration_proto_goTypes = nil
	file_powerssl_controller_v1_integration_proto_depIdxs = nil
}
