apiServerClient:
  authToken:
  client:
    addr:
    caFile:
    insecure:
    insecureSkipTLSVerify:
    serverNameOverride:
log:
  env: development
telemetry:
  meter:
    addr:
    exporter: prometheus
  tracer:
    exporter: jaeger
