apiServerClient:
  authToken:
  client:
    addr: localhost:8082
    caFile: local/certs/ca.pem
    insecure: false
    insecureSkipTLSVerify: false
    serverNameOverride:
temporalClient:
  caFile: local/certs/ca.pem
  disableHealthCheck:
  healthCheckTimeout:
  hostPort: localhost:7233
  identity:
  namespace: powerssl
  tlsCertFile:
  tlsKeyFile:
telemetry:
  meter:
    addr: localhost:9096
    exporter: prometheus
  tracer:
    exporter: jaeger
log:
  env: development
vaultClient:
  appRoleID:
  appRoleSecretID:
  caFile: local/certs/ca.pem
  token:
  url: https://localhost:8200
