# Default powerssl chart values which are recommended.
# Make sure to activate your used integration.
apiserver:
  name: api
  image:
    repository: powerssl/apiserver
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: false
    annotations: {}
    path: /
    hosts:
      - apiserver.127.0.0.1.nip.io
    tls: []
    #  - secretName: example-tls-secret
    #    hosts:
    #      - apiserver.127.0.0.1.nip.io

controller:
  name: controller
  image:
    repository: powerssl/controller
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081

signer:
  name: signer
  image:
    repository: powerssl/signer
    tag: latest
    pullPolicy: IfNotPresent

integration:
  acme:
    enabled: false
    name: acme
    image:
      repository: powerssl/integration-acme
      tag: latest
      pullPolicy: IfNotPresent
  cloudflare:
    enabled: false
    name: cloudflare
    image:
      repository: powerssl/integration/cloudflare
      tag: latest
      pullPolicy: IfNotPresent

