apiServerClient:
  authToken:
  client:
    addr: localhost:8082
    caFile: local/certs/ca.pem
    insecure: false
    insecureSkipTLSVerify: false
    serverNameOverride:
log:
  env: development
metrics:
  addr: localhost:9093
server:
  addr: localhost:8083
  caFile: local/certs/ca.pem
  certFile:
  commonName: localhost
  insecure: false
  keyFile:
  vaultRole:
  vaultToken:
  vaultURL: https://localhost:8200
temporalClient:
  caFile: local/certs/ca.pem
  disableHealthCheck:
  healthCheckTimeout:
  hostPort: localhost:7233
  identity:
  namespace: powerssl
  tlsCertFile:
  tlsKeyFile:
tracer:
  implementation: jaeger
vaultClient:
  appRole:
    roleID:
    secretID:
  caFile: local/certs/ca.pem
  token:
  url: https://localhost:8200
