// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: powerssl/apiserver/v1/acme_server.proto

package api // import "powerssl.io/pkg/apiserver/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import types "github.com/gogo/protobuf/types"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ACMEServer struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           *types.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime           *types.Timestamp `protobuf:"bytes,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	DisplayName          string           `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DirectoryUrl         string           `protobuf:"bytes,8,opt,name=directory_url,json=directoryUrl,proto3" json:"directory_url,omitempty"`
	IntegrationName      string           `protobuf:"bytes,9,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ACMEServer) Reset()         { *m = ACMEServer{} }
func (m *ACMEServer) String() string { return proto.CompactTextString(m) }
func (*ACMEServer) ProtoMessage()    {}
func (*ACMEServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_acme_server_024609cd35272263, []int{0}
}
func (m *ACMEServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACMEServer.Unmarshal(m, b)
}
func (m *ACMEServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACMEServer.Marshal(b, m, deterministic)
}
func (dst *ACMEServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACMEServer.Merge(dst, src)
}
func (m *ACMEServer) XXX_Size() int {
	return xxx_messageInfo_ACMEServer.Size(m)
}
func (m *ACMEServer) XXX_DiscardUnknown() {
	xxx_messageInfo_ACMEServer.DiscardUnknown(m)
}

var xxx_messageInfo_ACMEServer proto.InternalMessageInfo

func (m *ACMEServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ACMEServer) GetCreateTime() *types.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ACMEServer) GetUpdateTime() *types.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *ACMEServer) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ACMEServer) GetDirectoryUrl() string {
	if m != nil {
		return m.DirectoryUrl
	}
	return ""
}

func (m *ACMEServer) GetIntegrationName() string {
	if m != nil {
		return m.IntegrationName
	}
	return ""
}

type CreateACMEServerRequest struct {
	AcmeServer           *ACMEServer `protobuf:"bytes,1,opt,name=acme_server,json=acmeServer" json:"acme_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateACMEServerRequest) Reset()         { *m = CreateACMEServerRequest{} }
func (m *CreateACMEServerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateACMEServerRequest) ProtoMessage()    {}
func (*CreateACMEServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acme_server_024609cd35272263, []int{1}
}
func (m *CreateACMEServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateACMEServerRequest.Unmarshal(m, b)
}
func (m *CreateACMEServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateACMEServerRequest.Marshal(b, m, deterministic)
}
func (dst *CreateACMEServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateACMEServerRequest.Merge(dst, src)
}
func (m *CreateACMEServerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateACMEServerRequest.Size(m)
}
func (m *CreateACMEServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateACMEServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateACMEServerRequest proto.InternalMessageInfo

func (m *CreateACMEServerRequest) GetAcmeServer() *ACMEServer {
	if m != nil {
		return m.AcmeServer
	}
	return nil
}

type DeleteACMEServerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteACMEServerRequest) Reset()         { *m = DeleteACMEServerRequest{} }
func (m *DeleteACMEServerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteACMEServerRequest) ProtoMessage()    {}
func (*DeleteACMEServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acme_server_024609cd35272263, []int{2}
}
func (m *DeleteACMEServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteACMEServerRequest.Unmarshal(m, b)
}
func (m *DeleteACMEServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteACMEServerRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteACMEServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteACMEServerRequest.Merge(dst, src)
}
func (m *DeleteACMEServerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteACMEServerRequest.Size(m)
}
func (m *DeleteACMEServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteACMEServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteACMEServerRequest proto.InternalMessageInfo

func (m *DeleteACMEServerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetACMEServerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetACMEServerRequest) Reset()         { *m = GetACMEServerRequest{} }
func (m *GetACMEServerRequest) String() string { return proto.CompactTextString(m) }
func (*GetACMEServerRequest) ProtoMessage()    {}
func (*GetACMEServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acme_server_024609cd35272263, []int{3}
}
func (m *GetACMEServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetACMEServerRequest.Unmarshal(m, b)
}
func (m *GetACMEServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetACMEServerRequest.Marshal(b, m, deterministic)
}
func (dst *GetACMEServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetACMEServerRequest.Merge(dst, src)
}
func (m *GetACMEServerRequest) XXX_Size() int {
	return xxx_messageInfo_GetACMEServerRequest.Size(m)
}
func (m *GetACMEServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetACMEServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetACMEServerRequest proto.InternalMessageInfo

func (m *GetACMEServerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListACMEServersRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListACMEServersRequest) Reset()         { *m = ListACMEServersRequest{} }
func (m *ListACMEServersRequest) String() string { return proto.CompactTextString(m) }
func (*ListACMEServersRequest) ProtoMessage()    {}
func (*ListACMEServersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acme_server_024609cd35272263, []int{4}
}
func (m *ListACMEServersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListACMEServersRequest.Unmarshal(m, b)
}
func (m *ListACMEServersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListACMEServersRequest.Marshal(b, m, deterministic)
}
func (dst *ListACMEServersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListACMEServersRequest.Merge(dst, src)
}
func (m *ListACMEServersRequest) XXX_Size() int {
	return xxx_messageInfo_ListACMEServersRequest.Size(m)
}
func (m *ListACMEServersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListACMEServersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListACMEServersRequest proto.InternalMessageInfo

func (m *ListACMEServersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListACMEServersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListACMEServersResponse struct {
	AcmeServers          []*ACMEServer `protobuf:"bytes,1,rep,name=acme_servers,json=acmeServers" json:"acme_servers,omitempty"`
	NextPageToken        string        `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListACMEServersResponse) Reset()         { *m = ListACMEServersResponse{} }
func (m *ListACMEServersResponse) String() string { return proto.CompactTextString(m) }
func (*ListACMEServersResponse) ProtoMessage()    {}
func (*ListACMEServersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acme_server_024609cd35272263, []int{5}
}
func (m *ListACMEServersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListACMEServersResponse.Unmarshal(m, b)
}
func (m *ListACMEServersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListACMEServersResponse.Marshal(b, m, deterministic)
}
func (dst *ListACMEServersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListACMEServersResponse.Merge(dst, src)
}
func (m *ListACMEServersResponse) XXX_Size() int {
	return xxx_messageInfo_ListACMEServersResponse.Size(m)
}
func (m *ListACMEServersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListACMEServersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListACMEServersResponse proto.InternalMessageInfo

func (m *ListACMEServersResponse) GetAcmeServers() []*ACMEServer {
	if m != nil {
		return m.AcmeServers
	}
	return nil
}

func (m *ListACMEServersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type UpdateACMEServerRequest struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AcmeServer           *ACMEServer `protobuf:"bytes,2,opt,name=acme_server,json=acmeServer" json:"acme_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateACMEServerRequest) Reset()         { *m = UpdateACMEServerRequest{} }
func (m *UpdateACMEServerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateACMEServerRequest) ProtoMessage()    {}
func (*UpdateACMEServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acme_server_024609cd35272263, []int{6}
}
func (m *UpdateACMEServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateACMEServerRequest.Unmarshal(m, b)
}
func (m *UpdateACMEServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateACMEServerRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateACMEServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateACMEServerRequest.Merge(dst, src)
}
func (m *UpdateACMEServerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateACMEServerRequest.Size(m)
}
func (m *UpdateACMEServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateACMEServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateACMEServerRequest proto.InternalMessageInfo

func (m *UpdateACMEServerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateACMEServerRequest) GetAcmeServer() *ACMEServer {
	if m != nil {
		return m.AcmeServer
	}
	return nil
}

func init() {
	proto.RegisterType((*ACMEServer)(nil), "powerssl.apiserver.v1.ACMEServer")
	proto.RegisterType((*CreateACMEServerRequest)(nil), "powerssl.apiserver.v1.CreateACMEServerRequest")
	proto.RegisterType((*DeleteACMEServerRequest)(nil), "powerssl.apiserver.v1.DeleteACMEServerRequest")
	proto.RegisterType((*GetACMEServerRequest)(nil), "powerssl.apiserver.v1.GetACMEServerRequest")
	proto.RegisterType((*ListACMEServersRequest)(nil), "powerssl.apiserver.v1.ListACMEServersRequest")
	proto.RegisterType((*ListACMEServersResponse)(nil), "powerssl.apiserver.v1.ListACMEServersResponse")
	proto.RegisterType((*UpdateACMEServerRequest)(nil), "powerssl.apiserver.v1.UpdateACMEServerRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ACMEServerService service

type ACMEServerServiceClient interface {
	Create(ctx context.Context, in *CreateACMEServerRequest, opts ...grpc.CallOption) (*ACMEServer, error)
	Delete(ctx context.Context, in *DeleteACMEServerRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Get(ctx context.Context, in *GetACMEServerRequest, opts ...grpc.CallOption) (*ACMEServer, error)
	List(ctx context.Context, in *ListACMEServersRequest, opts ...grpc.CallOption) (*ListACMEServersResponse, error)
	Update(ctx context.Context, in *UpdateACMEServerRequest, opts ...grpc.CallOption) (*ACMEServer, error)
}

type aCMEServerServiceClient struct {
	cc *grpc.ClientConn
}

func NewACMEServerServiceClient(cc *grpc.ClientConn) ACMEServerServiceClient {
	return &aCMEServerServiceClient{cc}
}

func (c *aCMEServerServiceClient) Create(ctx context.Context, in *CreateACMEServerRequest, opts ...grpc.CallOption) (*ACMEServer, error) {
	out := new(ACMEServer)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.ACMEServerService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCMEServerServiceClient) Delete(ctx context.Context, in *DeleteACMEServerRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.ACMEServerService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCMEServerServiceClient) Get(ctx context.Context, in *GetACMEServerRequest, opts ...grpc.CallOption) (*ACMEServer, error) {
	out := new(ACMEServer)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.ACMEServerService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCMEServerServiceClient) List(ctx context.Context, in *ListACMEServersRequest, opts ...grpc.CallOption) (*ListACMEServersResponse, error) {
	out := new(ListACMEServersResponse)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.ACMEServerService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aCMEServerServiceClient) Update(ctx context.Context, in *UpdateACMEServerRequest, opts ...grpc.CallOption) (*ACMEServer, error) {
	out := new(ACMEServer)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.ACMEServerService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ACMEServerService service

type ACMEServerServiceServer interface {
	Create(context.Context, *CreateACMEServerRequest) (*ACMEServer, error)
	Delete(context.Context, *DeleteACMEServerRequest) (*types.Empty, error)
	Get(context.Context, *GetACMEServerRequest) (*ACMEServer, error)
	List(context.Context, *ListACMEServersRequest) (*ListACMEServersResponse, error)
	Update(context.Context, *UpdateACMEServerRequest) (*ACMEServer, error)
}

func RegisterACMEServerServiceServer(s *grpc.Server, srv ACMEServerServiceServer) {
	s.RegisterService(&_ACMEServerService_serviceDesc, srv)
}

func _ACMEServerService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateACMEServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServerServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.ACMEServerService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServerServiceServer).Create(ctx, req.(*CreateACMEServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACMEServerService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteACMEServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServerServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.ACMEServerService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServerServiceServer).Delete(ctx, req.(*DeleteACMEServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACMEServerService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetACMEServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServerServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.ACMEServerService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServerServiceServer).Get(ctx, req.(*GetACMEServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACMEServerService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListACMEServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServerServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.ACMEServerService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServerServiceServer).List(ctx, req.(*ListACMEServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ACMEServerService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateACMEServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ACMEServerServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.ACMEServerService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ACMEServerServiceServer).Update(ctx, req.(*UpdateACMEServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ACMEServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "powerssl.apiserver.v1.ACMEServerService",
	HandlerType: (*ACMEServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ACMEServerService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ACMEServerService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ACMEServerService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ACMEServerService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ACMEServerService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "powerssl/apiserver/v1/acme_server.proto",
}

func init() {
	proto.RegisterFile("powerssl/apiserver/v1/acme_server.proto", fileDescriptor_acme_server_024609cd35272263)
}

var fileDescriptor_acme_server_024609cd35272263 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xd3, 0x36, 0x6a, 0xc6, 0xad, 0x42, 0x57, 0xd0, 0x44, 0x2e, 0x15, 0xa9, 0x8b, 0x42,
	0x09, 0xd4, 0x56, 0xc2, 0x8d, 0x8a, 0x03, 0xfd, 0x50, 0x2f, 0x80, 0x50, 0x9a, 0x5e, 0x90, 0x90,
	0xe5, 0x26, 0x43, 0xb4, 0xaa, 0x63, 0xbb, 0xbb, 0x9b, 0x94, 0x14, 0x81, 0x10, 0x17, 0xc4, 0x01,
	0x71, 0xe0, 0xa7, 0xf1, 0x17, 0xf8, 0x21, 0x68, 0x77, 0xf3, 0x61, 0x25, 0xb1, 0x6a, 0x71, 0x89,
	0xec, 0xd9, 0xf7, 0xde, 0x8c, 0xdf, 0xbc, 0xd8, 0xf0, 0x28, 0x8e, 0xae, 0x91, 0x71, 0x1e, 0xb8,
	0x7e, 0x4c, 0x39, 0xb2, 0x01, 0x32, 0x77, 0x50, 0x77, 0xfd, 0x76, 0x0f, 0x3d, 0x7d, 0xeb, 0xc4,
	0x2c, 0x12, 0x11, 0xb9, 0x37, 0x06, 0x3a, 0x13, 0xa0, 0x33, 0xa8, 0x5b, 0xf7, 0xbb, 0x51, 0xd4,
	0x0d, 0x50, 0xb2, 0x5d, 0x3f, 0x0c, 0x23, 0xe1, 0x0b, 0x1a, 0x85, 0x5c, 0x93, 0xac, 0xad, 0xd1,
	0xa9, 0xba, 0xbb, 0xe8, 0x7f, 0x70, 0xb1, 0x17, 0x8b, 0xe1, 0xe8, 0xf0, 0xc1, 0xec, 0xa1, 0xa0,
	0x3d, 0xe4, 0xc2, 0xef, 0xc5, 0x1a, 0x60, 0xff, 0xcc, 0x01, 0xbc, 0x3c, 0x7a, 0x7d, 0x72, 0xa6,
	0xba, 0x11, 0x02, 0xcb, 0xa1, 0xdf, 0xc3, 0xb2, 0x51, 0x31, 0xf6, 0x0a, 0x4d, 0x75, 0x4d, 0x0e,
	0xc0, 0x6c, 0x33, 0xf4, 0x05, 0x7a, 0x92, 0x5c, 0xce, 0x55, 0x8c, 0x3d, 0xb3, 0x61, 0x39, 0x5a,
	0xd9, 0x19, 0x2b, 0x3b, 0xad, 0xb1, 0x72, 0x13, 0x34, 0x5c, 0x16, 0x24, 0xb9, 0x1f, 0x77, 0x26,
	0xe4, 0xa5, 0xdb, 0xc9, 0x1a, 0xae, 0xc8, 0x3b, 0xb0, 0xd6, 0xa1, 0x3c, 0x0e, 0xfc, 0xa1, 0xa7,
	0xa6, 0x5a, 0x56, 0x53, 0x99, 0xa3, 0xda, 0x1b, 0x39, 0xdc, 0x2e, 0xac, 0x77, 0x28, 0xc3, 0xb6,
	0x88, 0xd8, 0xd0, 0xeb, 0xb3, 0xa0, 0xbc, 0xaa, 0x30, 0x6b, 0x93, 0xe2, 0x39, 0x0b, 0xc8, 0x63,
	0xb8, 0x43, 0x43, 0x81, 0x5d, 0xa6, 0x8c, 0xd3, 0x5a, 0x05, 0x85, 0x2b, 0x26, 0xea, 0x52, 0xcf,
	0x7e, 0x0f, 0xa5, 0x23, 0x35, 0xfd, 0xd4, 0x94, 0x26, 0x5e, 0xf5, 0x91, 0x0b, 0x72, 0x08, 0x66,
	0x62, 0x65, 0xca, 0x22, 0xb3, 0xb1, 0xe3, 0x2c, 0xdc, 0x99, 0x93, 0xa0, 0x83, 0x64, 0xe9, 0x6b,
	0x7b, 0x1f, 0x4a, 0xc7, 0x18, 0xe0, 0x22, 0xf9, 0x05, 0xd6, 0xdb, 0x35, 0xb8, 0x7b, 0x8a, 0x22,
	0x1b, 0xb6, 0x05, 0x9b, 0xaf, 0x28, 0x4f, 0x80, 0xf9, 0x18, 0xbd, 0x05, 0x85, 0xd8, 0xef, 0xa2,
	0xc7, 0xe9, 0x8d, 0xa6, 0xac, 0x34, 0x57, 0x65, 0xe1, 0x8c, 0xde, 0x20, 0xd9, 0x06, 0x50, 0x87,
	0x22, 0xba, 0xc4, 0x50, 0x2d, 0xb7, 0xd0, 0x54, 0xf0, 0x96, 0x2c, 0xd8, 0xdf, 0x0d, 0x28, 0xcd,
	0xc9, 0xf2, 0x38, 0x0a, 0x39, 0x92, 0x63, 0x58, 0x4b, 0x18, 0xc2, 0xcb, 0x46, 0x65, 0x29, 0x9b,
	0x23, 0xe6, 0xd4, 0x11, 0x4e, 0xaa, 0x50, 0x0c, 0xf1, 0xa3, 0xf0, 0xe6, 0xa6, 0x58, 0x97, 0xe5,
	0xb7, 0x93, 0x49, 0xae, 0xa0, 0x74, 0xae, 0xa2, 0x91, 0xc9, 0x8e, 0xd9, 0x6d, 0xe5, 0xfe, 0x63,
	0x5b, 0x8d, 0x5f, 0x2b, 0xb0, 0x31, 0x3d, 0x92, 0xbf, 0xb4, 0x8d, 0xe4, 0xab, 0x01, 0x79, 0x9d,
	0x11, 0xe2, 0xa4, 0xe8, 0xa5, 0x44, 0xc8, 0xba, 0xbd, 0xbf, 0xbd, 0xfb, 0xed, 0xcf, 0xdf, 0xdf,
	0xb9, 0x6d, 0xbb, 0x38, 0x7e, 0x45, 0x8c, 0x7c, 0x7a, 0x9e, 0x18, 0x8c, 0x30, 0xc8, 0xeb, 0x18,
	0xa5, 0x4e, 0x90, 0x92, 0x32, 0x6b, 0x73, 0xee, 0xaf, 0x77, 0x22, 0x5f, 0x17, 0x76, 0x45, 0xb5,
	0xb5, 0x6a, 0x65, 0xd9, 0xf6, 0x93, 0x74, 0xf0, 0x45, 0xa2, 0xb9, 0x5b, 0xfb, 0x4c, 0xae, 0x61,
	0xe9, 0x14, 0x05, 0x79, 0x92, 0xd2, 0x70, 0x51, 0x4e, 0xb3, 0x3c, 0xef, 0xa8, 0x31, 0x49, 0x6f,
	0xfc, 0x05, 0x96, 0x65, 0x02, 0xc9, 0x7e, 0x8a, 0xd8, 0xe2, 0xd4, 0x5b, 0x4e, 0x56, 0xb8, 0x4e,
	0xb3, 0x5d, 0x52, 0x83, 0x6c, 0x90, 0x59, 0xe3, 0xc9, 0x0f, 0x03, 0xf2, 0x3a, 0x79, 0xa9, 0x6e,
	0xa7, 0x04, 0x33, 0xcb, 0xf3, 0x3f, 0x55, 0x6d, 0xab, 0x56, 0xea, 0xf3, 0x27, 0x17, 0x7f, 0x58,
	0x7d, 0xf7, 0x70, 0xa2, 0x48, 0x23, 0x37, 0xbe, 0xec, 0x26, 0xbe, 0x29, 0xf2, 0xfb, 0x30, 0xa8,
	0x1f, 0xf8, 0x31, 0xbd, 0xc8, 0xab, 0xf5, 0x3e, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x60, 0x79,
	0x0b, 0x4e, 0x7b, 0x06, 0x00, 0x00,
}
