// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apiserver/api/v1/certificate.proto

package api // import "powerssl.io/pkg/apiserver/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import types "github.com/gogo/protobuf/types"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DigestAlgorithm int32

const (
	DigestAlgorithm_DIGEST_ALGORITHM_UNSPECIFIED DigestAlgorithm = 0
	DigestAlgorithm_SHA1                         DigestAlgorithm = 1
	DigestAlgorithm_SHA256                       DigestAlgorithm = 2
)

var DigestAlgorithm_name = map[int32]string{
	0: "DIGEST_ALGORITHM_UNSPECIFIED",
	1: "SHA1",
	2: "SHA256",
}
var DigestAlgorithm_value = map[string]int32{
	"DIGEST_ALGORITHM_UNSPECIFIED": 0,
	"SHA1":                         1,
	"SHA256":                       2,
}

func (x DigestAlgorithm) String() string {
	return proto.EnumName(DigestAlgorithm_name, int32(x))
}
func (DigestAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{0}
}

type KeyAlgorithm int32

const (
	KeyAlgorithm_KEY_ALGORITHM_UNSPECIFIED KeyAlgorithm = 0
	KeyAlgorithm_RSA                       KeyAlgorithm = 1
)

var KeyAlgorithm_name = map[int32]string{
	0: "KEY_ALGORITHM_UNSPECIFIED",
	1: "RSA",
}
var KeyAlgorithm_value = map[string]int32{
	"KEY_ALGORITHM_UNSPECIFIED": 0,
	"RSA":                       1,
}

func (x KeyAlgorithm) String() string {
	return proto.EnumName(KeyAlgorithm_name, int32(x))
}
func (KeyAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{1}
}

// A Certificate ...
type Certificate struct {
	// The resource name of the certificate.
	// Certificate names have the form `certificates/{certificate_id}`.
	// The name is ignored when creating a certificate.
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           *types.Timestamp  `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime           *types.Timestamp  `protobuf:"bytes,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	DisplayName          string            `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Title                string            `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels               map[string]string `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Dnsnames             []string          `protobuf:"bytes,8,rep,name=dnsnames" json:"dnsnames,omitempty"`
	KeyAlgorithm         KeyAlgorithm      `protobuf:"varint,9,opt,name=key_algorithm,json=keyAlgorithm,proto3,enum=powerssl.apiserver.v1.KeyAlgorithm" json:"key_algorithm,omitempty"`
	KeySize              int32             `protobuf:"varint,10,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	DigestAlgorithm      DigestAlgorithm   `protobuf:"varint,11,opt,name=digest_algorithm,json=digestAlgorithm,proto3,enum=powerssl.apiserver.v1.DigestAlgorithm" json:"digest_algorithm,omitempty"`
	AutoRenew            bool              `protobuf:"varint,12,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{0}
}
func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (dst *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(dst, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Certificate) GetCreateTime() *types.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Certificate) GetUpdateTime() *types.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Certificate) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Certificate) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Certificate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Certificate) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Certificate) GetDnsnames() []string {
	if m != nil {
		return m.Dnsnames
	}
	return nil
}

func (m *Certificate) GetKeyAlgorithm() KeyAlgorithm {
	if m != nil {
		return m.KeyAlgorithm
	}
	return KeyAlgorithm_KEY_ALGORITHM_UNSPECIFIED
}

func (m *Certificate) GetKeySize() int32 {
	if m != nil {
		return m.KeySize
	}
	return 0
}

func (m *Certificate) GetDigestAlgorithm() DigestAlgorithm {
	if m != nil {
		return m.DigestAlgorithm
	}
	return DigestAlgorithm_DIGEST_ALGORITHM_UNSPECIFIED
}

func (m *Certificate) GetAutoRenew() bool {
	if m != nil {
		return m.AutoRenew
	}
	return false
}

// Request message for CertificateService.Create.
type CreateCertificateRequest struct {
	// The certificate to create.
	Certificate          *Certificate `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateCertificateRequest) Reset()         { *m = CreateCertificateRequest{} }
func (m *CreateCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCertificateRequest) ProtoMessage()    {}
func (*CreateCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{1}
}
func (m *CreateCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCertificateRequest.Unmarshal(m, b)
}
func (m *CreateCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCertificateRequest.Merge(dst, src)
}
func (m *CreateCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCertificateRequest.Size(m)
}
func (m *CreateCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCertificateRequest proto.InternalMessageInfo

func (m *CreateCertificateRequest) GetCertificate() *Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

// Request message for CertificateService.Delete.
type DeleteCertificateRequest struct {
	// The name of the certificate to delete.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCertificateRequest) Reset()         { *m = DeleteCertificateRequest{} }
func (m *DeleteCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCertificateRequest) ProtoMessage()    {}
func (*DeleteCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{2}
}
func (m *DeleteCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCertificateRequest.Unmarshal(m, b)
}
func (m *DeleteCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCertificateRequest.Merge(dst, src)
}
func (m *DeleteCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCertificateRequest.Size(m)
}
func (m *DeleteCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCertificateRequest proto.InternalMessageInfo

func (m *DeleteCertificateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Request message for CertificateService.Get.
type GetCertificateRequest struct {
	// The name of the certificate to retrieve.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCertificateRequest) Reset()         { *m = GetCertificateRequest{} }
func (m *GetCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*GetCertificateRequest) ProtoMessage()    {}
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{3}
}
func (m *GetCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCertificateRequest.Unmarshal(m, b)
}
func (m *GetCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *GetCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCertificateRequest.Merge(dst, src)
}
func (m *GetCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_GetCertificateRequest.Size(m)
}
func (m *GetCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCertificateRequest proto.InternalMessageInfo

func (m *GetCertificateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Request message for CertificateService.List.
type ListCertificatesRequest struct {
	// Requested page size. Server may return fewer certificates than requested.
	// If unspecified, server will pick an appropriate default.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A token identifying a page of results the server should return.
	// Typically, this is the value of
	// [ListCertificatesResponse.next_page_token][powerssl.apiserver.v1.ListCertificatesResponse.next_page_token].
	// returned from the previous call to `List` method.
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCertificatesRequest) Reset()         { *m = ListCertificatesRequest{} }
func (m *ListCertificatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCertificatesRequest) ProtoMessage()    {}
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{4}
}
func (m *ListCertificatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCertificatesRequest.Unmarshal(m, b)
}
func (m *ListCertificatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCertificatesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCertificatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCertificatesRequest.Merge(dst, src)
}
func (m *ListCertificatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCertificatesRequest.Size(m)
}
func (m *ListCertificatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCertificatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCertificatesRequest proto.InternalMessageInfo

func (m *ListCertificatesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCertificatesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// Response message for CertificateService.List.
type ListCertificatesResponse struct {
	// The list of certificates.
	Certificates []*Certificate `protobuf:"bytes,1,rep,name=certificates" json:"certificates,omitempty"`
	// A token to retrieve next page of results.
	// Pass this value in the
	// [ListCertificatesRequest.page_token][powerssl.apiserver.v1.ListCertificatesRequest.page_token]
	// field in the subsequent call to `List` method to retrieve the next
	// page of results.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCertificatesResponse) Reset()         { *m = ListCertificatesResponse{} }
func (m *ListCertificatesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCertificatesResponse) ProtoMessage()    {}
func (*ListCertificatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{5}
}
func (m *ListCertificatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCertificatesResponse.Unmarshal(m, b)
}
func (m *ListCertificatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCertificatesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCertificatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCertificatesResponse.Merge(dst, src)
}
func (m *ListCertificatesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCertificatesResponse.Size(m)
}
func (m *ListCertificatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCertificatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCertificatesResponse proto.InternalMessageInfo

func (m *ListCertificatesResponse) GetCertificates() []*Certificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *ListCertificatesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Request message for CertificateService.Update.
type UpdateCertificateRequest struct {
	// The name of the certificate to update.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The certificate to update with. The name must match or be empty.
	Certificate          *Certificate `protobuf:"bytes,2,opt,name=certificate" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateCertificateRequest) Reset()         { *m = UpdateCertificateRequest{} }
func (m *UpdateCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCertificateRequest) ProtoMessage()    {}
func (*UpdateCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_5f3c4d50555ba436, []int{6}
}
func (m *UpdateCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCertificateRequest.Unmarshal(m, b)
}
func (m *UpdateCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCertificateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCertificateRequest.Merge(dst, src)
}
func (m *UpdateCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCertificateRequest.Size(m)
}
func (m *UpdateCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCertificateRequest proto.InternalMessageInfo

func (m *UpdateCertificateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCertificateRequest) GetCertificate() *Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func init() {
	proto.RegisterType((*Certificate)(nil), "powerssl.apiserver.v1.Certificate")
	proto.RegisterMapType((map[string]string)(nil), "powerssl.apiserver.v1.Certificate.LabelsEntry")
	proto.RegisterType((*CreateCertificateRequest)(nil), "powerssl.apiserver.v1.CreateCertificateRequest")
	proto.RegisterType((*DeleteCertificateRequest)(nil), "powerssl.apiserver.v1.DeleteCertificateRequest")
	proto.RegisterType((*GetCertificateRequest)(nil), "powerssl.apiserver.v1.GetCertificateRequest")
	proto.RegisterType((*ListCertificatesRequest)(nil), "powerssl.apiserver.v1.ListCertificatesRequest")
	proto.RegisterType((*ListCertificatesResponse)(nil), "powerssl.apiserver.v1.ListCertificatesResponse")
	proto.RegisterType((*UpdateCertificateRequest)(nil), "powerssl.apiserver.v1.UpdateCertificateRequest")
	proto.RegisterEnum("powerssl.apiserver.v1.DigestAlgorithm", DigestAlgorithm_name, DigestAlgorithm_value)
	proto.RegisterEnum("powerssl.apiserver.v1.KeyAlgorithm", KeyAlgorithm_name, KeyAlgorithm_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CertificateService service

type CertificateServiceClient interface {
	// Creates a certificate, and returns the new Certificate.
	Create(ctx context.Context, in *CreateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error)
	// Deletes a certificate. Returns NOT_FOUND if the certificate does not exist.
	Delete(ctx context.Context, in *DeleteCertificateRequest, opts ...grpc.CallOption) (*types.Empty, error)
	// Gets a certificate. Returns NOT_FOUND if the certificate does not exist.
	Get(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*Certificate, error)
	// Lists certificates. The order is unspecified but deterministic. Newly created
	// certificates will not necessarily be added to the end of this list.
	List(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error)
	// Updates a certificate. Returns INVALID_ARGUMENT if the name of the certificate
	// is non-empty and does equal the previous name.
	Update(ctx context.Context, in *UpdateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error)
}

type certificateServiceClient struct {
	cc *grpc.ClientConn
}

func NewCertificateServiceClient(cc *grpc.ClientConn) CertificateServiceClient {
	return &certificateServiceClient{cc}
}

func (c *certificateServiceClient) Create(ctx context.Context, in *CreateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error) {
	out := new(Certificate)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Delete(ctx context.Context, in *DeleteCertificateRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Get(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*Certificate, error) {
	out := new(Certificate)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) List(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error) {
	out := new(ListCertificatesResponse)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) Update(ctx context.Context, in *UpdateCertificateRequest, opts ...grpc.CallOption) (*Certificate, error) {
	out := new(Certificate)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CertificateService service

type CertificateServiceServer interface {
	// Creates a certificate, and returns the new Certificate.
	Create(context.Context, *CreateCertificateRequest) (*Certificate, error)
	// Deletes a certificate. Returns NOT_FOUND if the certificate does not exist.
	Delete(context.Context, *DeleteCertificateRequest) (*types.Empty, error)
	// Gets a certificate. Returns NOT_FOUND if the certificate does not exist.
	Get(context.Context, *GetCertificateRequest) (*Certificate, error)
	// Lists certificates. The order is unspecified but deterministic. Newly created
	// certificates will not necessarily be added to the end of this list.
	List(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error)
	// Updates a certificate. Returns INVALID_ARGUMENT if the name of the certificate
	// is non-empty and does equal the previous name.
	Update(context.Context, *UpdateCertificateRequest) (*Certificate, error)
}

func RegisterCertificateServiceServer(s *grpc.Server, srv CertificateServiceServer) {
	s.RegisterService(&_CertificateService_serviceDesc, srv)
}

func _CertificateService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Create(ctx, req.(*CreateCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Delete(ctx, req.(*DeleteCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Get(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).List(ctx, req.(*ListCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).Update(ctx, req.(*UpdateCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertificateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "powerssl.apiserver.v1.CertificateService",
	HandlerType: (*CertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CertificateService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CertificateService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CertificateService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CertificateService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CertificateService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiserver/api/v1/certificate.proto",
}

func init() {
	proto.RegisterFile("apiserver/api/v1/certificate.proto", fileDescriptor_certificate_5f3c4d50555ba436)
}

var fileDescriptor_certificate_5f3c4d50555ba436 = []byte{
	// 845 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xc6, 0x49, 0x9a, 0x26, 0xcf, 0x59, 0x1a, 0x8d, 0x58, 0x70, 0xdd, 0xad, 0xd6, 0x6b, 0xa0,
	0xb2, 0x0a, 0xb2, 0xd5, 0x20, 0x56, 0xb0, 0x2b, 0x0e, 0xa1, 0x49, 0xdb, 0x68, 0xcb, 0xb2, 0x38,
	0xe9, 0x01, 0x2e, 0xc1, 0x4d, 0xde, 0x86, 0x51, 0x1c, 0xdb, 0x78, 0x26, 0x59, 0x52, 0xc4, 0x01,
	0xc4, 0x09, 0x89, 0x13, 0xbf, 0x80, 0xdf, 0xc4, 0x5f, 0xe0, 0xc8, 0x8f, 0x40, 0x33, 0x76, 0x52,
	0x37, 0x89, 0xd9, 0x88, 0x5b, 0xe6, 0xcd, 0xfb, 0xde, 0xf7, 0xfc, 0xbd, 0xef, 0xd9, 0x01, 0xd3,
	0x8b, 0x28, 0xc3, 0x78, 0x86, 0xb1, 0xe3, 0x45, 0xd4, 0x99, 0x9d, 0x38, 0x03, 0x8c, 0x39, 0x7d,
	0x49, 0x07, 0x1e, 0x47, 0x3b, 0x8a, 0x43, 0x1e, 0x92, 0xfb, 0x51, 0xf8, 0x0a, 0x63, 0xc6, 0x7c,
	0x7b, 0x99, 0x6c, 0xcf, 0x4e, 0xf4, 0x07, 0xa3, 0x30, 0x1c, 0xf9, 0x28, 0x71, 0x5e, 0x10, 0x84,
	0xdc, 0xe3, 0x34, 0x0c, 0x58, 0x02, 0xd2, 0x0f, 0xd2, 0x5b, 0x79, 0xba, 0x9e, 0xbe, 0x74, 0x70,
	0x12, 0xf1, 0x79, 0x7a, 0xf9, 0x70, 0xf5, 0x92, 0xd3, 0x09, 0x32, 0xee, 0x4d, 0xa2, 0x24, 0xc1,
	0xfc, 0xa7, 0x04, 0xea, 0xe9, 0x6d, 0x23, 0x84, 0x40, 0x29, 0xf0, 0x26, 0xa8, 0x29, 0x86, 0x62,
	0x55, 0x5d, 0xf9, 0x9b, 0x3c, 0x05, 0x75, 0x10, 0xa3, 0xc7, 0xb1, 0x2f, 0xd0, 0x5a, 0xc1, 0x50,
	0x2c, 0xb5, 0xa1, 0xdb, 0x49, 0x69, 0x7b, 0x51, 0xda, 0xee, 0x2d, 0x4a, 0xbb, 0x90, 0xa4, 0x8b,
	0x80, 0x00, 0x4f, 0xa3, 0xe1, 0x12, 0x5c, 0x7c, 0x3d, 0x38, 0x49, 0x97, 0xe0, 0x47, 0x50, 0x1b,
	0x52, 0x16, 0xf9, 0xde, 0xbc, 0x2f, 0xbb, 0x2a, 0xc9, 0xae, 0xd4, 0x34, 0xf6, 0x5c, 0x34, 0xf7,
	0x16, 0xec, 0x70, 0xca, 0x7d, 0xd4, 0x76, 0xe4, 0x5d, 0x72, 0x20, 0x06, 0xa8, 0x43, 0x64, 0x83,
	0x98, 0x46, 0x42, 0x2a, 0xad, 0x9c, 0xe2, 0x6e, 0x43, 0xe4, 0x0c, 0xca, 0xbe, 0x77, 0x8d, 0x3e,
	0xd3, 0x76, 0x8d, 0xa2, 0xa5, 0x36, 0x6c, 0x7b, 0xa3, 0xf8, 0x76, 0x46, 0x1c, 0xfb, 0x52, 0x02,
	0xda, 0x01, 0x8f, 0xe7, 0x6e, 0x8a, 0x26, 0x3a, 0x54, 0x86, 0x01, 0x13, 0xdd, 0x31, 0xad, 0x62,
	0x14, 0xad, 0xaa, 0xbb, 0x3c, 0x93, 0x0b, 0xb8, 0x37, 0xc6, 0x79, 0xdf, 0xf3, 0x47, 0x61, 0x4c,
	0xf9, 0x77, 0x13, 0xad, 0x6a, 0x28, 0xd6, 0x9b, 0x8d, 0x77, 0x73, 0xa8, 0x9e, 0xe1, 0xbc, 0xb9,
	0x48, 0x75, 0x6b, 0xe3, 0xcc, 0x89, 0xec, 0x43, 0x45, 0x54, 0x62, 0xf4, 0x06, 0x35, 0x30, 0x14,
	0x6b, 0xc7, 0xdd, 0x1d, 0xe3, 0xbc, 0x4b, 0x6f, 0x90, 0x7c, 0x05, 0xf5, 0x21, 0x1d, 0x21, 0xe3,
	0x19, 0x1e, 0x55, 0xf2, 0x1c, 0xe5, 0xf0, 0xb4, 0x64, 0xfa, 0x2d, 0xd5, 0xde, 0xf0, 0x6e, 0x80,
	0x1c, 0x02, 0x78, 0x53, 0x1e, 0xf6, 0x63, 0x0c, 0xf0, 0x95, 0x56, 0x33, 0x14, 0xab, 0xe2, 0x56,
	0x45, 0xc4, 0x15, 0x01, 0xfd, 0x53, 0x50, 0x33, 0x4a, 0x90, 0x3a, 0x14, 0xc7, 0x38, 0x4f, 0x1d,
	0x23, 0x7e, 0x8a, 0x99, 0xcc, 0x3c, 0x7f, 0x9a, 0x58, 0xa5, 0xea, 0x26, 0x87, 0x27, 0x85, 0x4f,
	0x14, 0xf3, 0x5b, 0xd0, 0x4e, 0xa5, 0x37, 0x32, 0xb2, 0xba, 0xf8, 0xfd, 0x14, 0x19, 0x27, 0x2d,
	0x50, 0x33, 0x2b, 0x21, 0xeb, 0xa9, 0x0d, 0xf3, 0xf5, 0x63, 0x71, 0xb3, 0x30, 0xd3, 0x06, 0xad,
	0x85, 0x3e, 0x6e, 0x64, 0xd8, 0x60, 0x6e, 0xf3, 0x03, 0xb8, 0x7f, 0x8e, 0x7c, 0xcb, 0xe4, 0x2b,
	0x78, 0xe7, 0x92, 0xb2, 0x6c, 0x36, 0x5b, 0xa4, 0x1f, 0x40, 0x35, 0xf2, 0x46, 0x98, 0x8c, 0x48,
	0x91, 0x23, 0xaa, 0x88, 0x80, 0x9c, 0xd1, 0x21, 0x80, 0xbc, 0xe4, 0xe1, 0x18, 0x83, 0x54, 0x15,
	0x99, 0xde, 0x13, 0x01, 0xf3, 0x37, 0x05, 0xb4, 0xf5, 0xba, 0x2c, 0x0a, 0x03, 0x86, 0xe4, 0x0c,
	0x6a, 0x99, 0xe7, 0x63, 0x9a, 0x22, 0xed, 0xba, 0x8d, 0x2e, 0x77, 0x70, 0xe4, 0x08, 0xf6, 0x02,
	0xfc, 0x81, 0xf7, 0xd7, 0x1a, 0xb9, 0x27, 0xc2, 0x2f, 0x96, 0xcd, 0x70, 0xd0, 0xae, 0xe4, 0x06,
	0x6e, 0xa7, 0xc9, 0xea, 0xd8, 0x0a, 0xff, 0x6b, 0x6c, 0xc7, 0x1d, 0xd8, 0x5b, 0xb1, 0x25, 0x31,
	0xe0, 0x41, 0xab, 0x73, 0xde, 0xee, 0xf6, 0xfa, 0xcd, 0xcb, 0xf3, 0x2f, 0xdd, 0x4e, 0xef, 0xe2,
	0x8b, 0xfe, 0xd5, 0xf3, 0xee, 0x8b, 0xf6, 0x69, 0xe7, 0xac, 0xd3, 0x6e, 0xd5, 0xdf, 0x20, 0x15,
	0x28, 0x75, 0x2f, 0x9a, 0x27, 0x75, 0x85, 0x00, 0x94, 0xbb, 0x17, 0xcd, 0xc6, 0xc7, 0x8f, 0xeb,
	0x85, 0xe3, 0xc7, 0x50, 0xcb, 0x6e, 0x12, 0x39, 0x84, 0xfd, 0x67, 0xed, 0xaf, 0x73, 0x8b, 0xec,
	0x42, 0xd1, 0xed, 0x36, 0xeb, 0x4a, 0xe3, 0xcf, 0x1d, 0x20, 0x99, 0xfe, 0xba, 0x18, 0xcf, 0xe8,
	0x00, 0xc9, 0xaf, 0x0a, 0x94, 0x13, 0xcf, 0x12, 0x27, 0xef, 0xa9, 0x72, 0x2c, 0xad, 0x6f, 0x21,
	0x83, 0xf9, 0xfe, 0x2f, 0x7f, 0xfd, 0xfd, 0x47, 0xe1, 0xa1, 0x59, 0x5f, 0xf9, 0x26, 0xb0, 0x27,
	0x59, 0x81, 0x08, 0x87, 0x72, 0xe2, 0xeb, 0xdc, 0x2e, 0xf2, 0x6c, 0xaf, 0xbf, 0xbd, 0xf6, 0xb6,
	0x6d, 0x8b, 0x4f, 0x84, 0xf9, 0x48, 0x32, 0x1f, 0x1c, 0xef, 0x0b, 0xe6, 0x1f, 0xc5, 0x30, 0x3f,
	0xcb, 0xf2, 0x3b, 0xc7, 0x3f, 0x91, 0x1b, 0x28, 0x9e, 0x23, 0x27, 0x1f, 0xe6, 0x50, 0x6e, 0xdc,
	0x9c, 0xad, 0x9e, 0x3a, 0xe5, 0x26, 0xff, 0xc1, 0xfd, 0xb3, 0x02, 0x25, 0xb1, 0x15, 0x24, 0xef,
	0xd5, 0x9c, 0xb3, 0x8a, 0xba, 0xb3, 0x75, 0x7e, 0xb2, 0x62, 0xa6, 0x26, 0x9b, 0x21, 0x64, 0x6d,
	0x04, 0xe4, 0x77, 0x05, 0xca, 0xc9, 0x36, 0xe4, 0xca, 0x9e, 0xb7, 0x2c, 0x5b, 0xc9, 0x60, 0x4b,
	0x66, 0x4b, 0xcf, 0x97, 0xe1, 0x8e, 0x0b, 0x3e, 0x3f, 0xfa, 0xe6, 0xbd, 0x65, 0x51, 0x1a, 0x3a,
	0xd1, 0x78, 0xe4, 0xac, 0xfe, 0xaf, 0x78, 0xea, 0x45, 0xf4, 0xba, 0x2c, 0x47, 0xfd, 0xd1, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x50, 0x8b, 0x17, 0x43, 0x76, 0x08, 0x00, 0x00,
}
