// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apiserver/api/v1/certificate_issue.proto

package api // import "powerssl.io/pkg/apiserver/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import types "github.com/gogo/protobuf/types"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// A CertificateIssue ...
type CertificateIssue struct {
	// The resource name of the certificate issue.
	// CertificateIssue names have the form `certificates/{certificate_id}/issues/{issue_id}`.
	// The name is ignored when creating a certificate issue.
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           *types.Timestamp  `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	UpdateTime           *types.Timestamp  `protobuf:"bytes,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	DisplayName          string            `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Title                string            `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels               map[string]string `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Dnsnames             []string          `protobuf:"bytes,8,rep,name=dnsnames" json:"dnsnames,omitempty"`
	KeyAlgorithm         string            `protobuf:"bytes,9,opt,name=key_algorithm,json=keyAlgorithm,proto3" json:"key_algorithm,omitempty"`
	KeySize              int32             `protobuf:"varint,10,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	DigestAlgorithm      string            `protobuf:"bytes,11,opt,name=digest_algorithm,json=digestAlgorithm,proto3" json:"digest_algorithm,omitempty"`
	AutoRenew            bool              `protobuf:"varint,12,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CertificateIssue) Reset()         { *m = CertificateIssue{} }
func (m *CertificateIssue) String() string { return proto.CompactTextString(m) }
func (*CertificateIssue) ProtoMessage()    {}
func (*CertificateIssue) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_issue_bb99f45ab1c55a6f, []int{0}
}
func (m *CertificateIssue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateIssue.Unmarshal(m, b)
}
func (m *CertificateIssue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateIssue.Marshal(b, m, deterministic)
}
func (dst *CertificateIssue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateIssue.Merge(dst, src)
}
func (m *CertificateIssue) XXX_Size() int {
	return xxx_messageInfo_CertificateIssue.Size(m)
}
func (m *CertificateIssue) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateIssue.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateIssue proto.InternalMessageInfo

func (m *CertificateIssue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CertificateIssue) GetCreateTime() *types.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *CertificateIssue) GetUpdateTime() *types.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *CertificateIssue) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CertificateIssue) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CertificateIssue) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CertificateIssue) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CertificateIssue) GetDnsnames() []string {
	if m != nil {
		return m.Dnsnames
	}
	return nil
}

func (m *CertificateIssue) GetKeyAlgorithm() string {
	if m != nil {
		return m.KeyAlgorithm
	}
	return ""
}

func (m *CertificateIssue) GetKeySize() int32 {
	if m != nil {
		return m.KeySize
	}
	return 0
}

func (m *CertificateIssue) GetDigestAlgorithm() string {
	if m != nil {
		return m.DigestAlgorithm
	}
	return ""
}

func (m *CertificateIssue) GetAutoRenew() bool {
	if m != nil {
		return m.AutoRenew
	}
	return false
}

type CreateCertificateIssueRequest struct {
	Parent               string            `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	CertificateIssue     *CertificateIssue `protobuf:"bytes,2,opt,name=certificate_issue,json=certificateIssue" json:"certificate_issue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCertificateIssueRequest) Reset()         { *m = CreateCertificateIssueRequest{} }
func (m *CreateCertificateIssueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCertificateIssueRequest) ProtoMessage()    {}
func (*CreateCertificateIssueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_issue_bb99f45ab1c55a6f, []int{1}
}
func (m *CreateCertificateIssueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCertificateIssueRequest.Unmarshal(m, b)
}
func (m *CreateCertificateIssueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCertificateIssueRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCertificateIssueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCertificateIssueRequest.Merge(dst, src)
}
func (m *CreateCertificateIssueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCertificateIssueRequest.Size(m)
}
func (m *CreateCertificateIssueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCertificateIssueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCertificateIssueRequest proto.InternalMessageInfo

func (m *CreateCertificateIssueRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateCertificateIssueRequest) GetCertificateIssue() *CertificateIssue {
	if m != nil {
		return m.CertificateIssue
	}
	return nil
}

type DeleteCertificateIssueRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCertificateIssueRequest) Reset()         { *m = DeleteCertificateIssueRequest{} }
func (m *DeleteCertificateIssueRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCertificateIssueRequest) ProtoMessage()    {}
func (*DeleteCertificateIssueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_issue_bb99f45ab1c55a6f, []int{2}
}
func (m *DeleteCertificateIssueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCertificateIssueRequest.Unmarshal(m, b)
}
func (m *DeleteCertificateIssueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCertificateIssueRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCertificateIssueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCertificateIssueRequest.Merge(dst, src)
}
func (m *DeleteCertificateIssueRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCertificateIssueRequest.Size(m)
}
func (m *DeleteCertificateIssueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCertificateIssueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCertificateIssueRequest proto.InternalMessageInfo

func (m *DeleteCertificateIssueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCertificateIssueRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCertificateIssueRequest) Reset()         { *m = GetCertificateIssueRequest{} }
func (m *GetCertificateIssueRequest) String() string { return proto.CompactTextString(m) }
func (*GetCertificateIssueRequest) ProtoMessage()    {}
func (*GetCertificateIssueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_issue_bb99f45ab1c55a6f, []int{3}
}
func (m *GetCertificateIssueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCertificateIssueRequest.Unmarshal(m, b)
}
func (m *GetCertificateIssueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCertificateIssueRequest.Marshal(b, m, deterministic)
}
func (dst *GetCertificateIssueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCertificateIssueRequest.Merge(dst, src)
}
func (m *GetCertificateIssueRequest) XXX_Size() int {
	return xxx_messageInfo_GetCertificateIssueRequest.Size(m)
}
func (m *GetCertificateIssueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCertificateIssueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCertificateIssueRequest proto.InternalMessageInfo

func (m *GetCertificateIssueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListCertificateIssuesRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCertificateIssuesRequest) Reset()         { *m = ListCertificateIssuesRequest{} }
func (m *ListCertificateIssuesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCertificateIssuesRequest) ProtoMessage()    {}
func (*ListCertificateIssuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_issue_bb99f45ab1c55a6f, []int{4}
}
func (m *ListCertificateIssuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCertificateIssuesRequest.Unmarshal(m, b)
}
func (m *ListCertificateIssuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCertificateIssuesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCertificateIssuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCertificateIssuesRequest.Merge(dst, src)
}
func (m *ListCertificateIssuesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCertificateIssuesRequest.Size(m)
}
func (m *ListCertificateIssuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCertificateIssuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCertificateIssuesRequest proto.InternalMessageInfo

func (m *ListCertificateIssuesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListCertificateIssuesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCertificateIssuesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListCertificateIssuesResponse struct {
	CertificateIssues    []*CertificateIssue `protobuf:"bytes,1,rep,name=certificate_issues,json=certificateIssues" json:"certificate_issues,omitempty"`
	NextPageToken        string              `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListCertificateIssuesResponse) Reset()         { *m = ListCertificateIssuesResponse{} }
func (m *ListCertificateIssuesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCertificateIssuesResponse) ProtoMessage()    {}
func (*ListCertificateIssuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_issue_bb99f45ab1c55a6f, []int{5}
}
func (m *ListCertificateIssuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCertificateIssuesResponse.Unmarshal(m, b)
}
func (m *ListCertificateIssuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCertificateIssuesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCertificateIssuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCertificateIssuesResponse.Merge(dst, src)
}
func (m *ListCertificateIssuesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCertificateIssuesResponse.Size(m)
}
func (m *ListCertificateIssuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCertificateIssuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCertificateIssuesResponse proto.InternalMessageInfo

func (m *ListCertificateIssuesResponse) GetCertificateIssues() []*CertificateIssue {
	if m != nil {
		return m.CertificateIssues
	}
	return nil
}

func (m *ListCertificateIssuesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type UpdateCertificateIssueRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CertificateIssue     *CertificateIssue `protobuf:"bytes,2,opt,name=certificate_issue,json=certificateIssue" json:"certificate_issue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateCertificateIssueRequest) Reset()         { *m = UpdateCertificateIssueRequest{} }
func (m *UpdateCertificateIssueRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCertificateIssueRequest) ProtoMessage()    {}
func (*UpdateCertificateIssueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_certificate_issue_bb99f45ab1c55a6f, []int{6}
}
func (m *UpdateCertificateIssueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCertificateIssueRequest.Unmarshal(m, b)
}
func (m *UpdateCertificateIssueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCertificateIssueRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCertificateIssueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCertificateIssueRequest.Merge(dst, src)
}
func (m *UpdateCertificateIssueRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCertificateIssueRequest.Size(m)
}
func (m *UpdateCertificateIssueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCertificateIssueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCertificateIssueRequest proto.InternalMessageInfo

func (m *UpdateCertificateIssueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCertificateIssueRequest) GetCertificateIssue() *CertificateIssue {
	if m != nil {
		return m.CertificateIssue
	}
	return nil
}

func init() {
	proto.RegisterType((*CertificateIssue)(nil), "powerssl.apiserver.v1.CertificateIssue")
	proto.RegisterMapType((map[string]string)(nil), "powerssl.apiserver.v1.CertificateIssue.LabelsEntry")
	proto.RegisterType((*CreateCertificateIssueRequest)(nil), "powerssl.apiserver.v1.CreateCertificateIssueRequest")
	proto.RegisterType((*DeleteCertificateIssueRequest)(nil), "powerssl.apiserver.v1.DeleteCertificateIssueRequest")
	proto.RegisterType((*GetCertificateIssueRequest)(nil), "powerssl.apiserver.v1.GetCertificateIssueRequest")
	proto.RegisterType((*ListCertificateIssuesRequest)(nil), "powerssl.apiserver.v1.ListCertificateIssuesRequest")
	proto.RegisterType((*ListCertificateIssuesResponse)(nil), "powerssl.apiserver.v1.ListCertificateIssuesResponse")
	proto.RegisterType((*UpdateCertificateIssueRequest)(nil), "powerssl.apiserver.v1.UpdateCertificateIssueRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CertificateIssueService service

type CertificateIssueServiceClient interface {
	// Creates a certificate, and returns the new CertificateIssue.
	Create(ctx context.Context, in *CreateCertificateIssueRequest, opts ...grpc.CallOption) (*CertificateIssue, error)
	// Deletes a certificate. Returns NOT_FOUND if the certificate does not exist.
	Delete(ctx context.Context, in *DeleteCertificateIssueRequest, opts ...grpc.CallOption) (*types.Empty, error)
	// Gets a certificate. Returns NOT_FOUND if the certificate does not exist.
	Get(ctx context.Context, in *GetCertificateIssueRequest, opts ...grpc.CallOption) (*CertificateIssue, error)
	// Lists certificates. The order is unspecified but deterministic. Newly created
	// certificates will not necessarily be added to the end of this list.
	List(ctx context.Context, in *ListCertificateIssuesRequest, opts ...grpc.CallOption) (*ListCertificateIssuesResponse, error)
	// Updates a certificate. Returns INVALID_ARGUMENT if the name of the certificate
	// is non-empty and does equal the previous name.
	Update(ctx context.Context, in *UpdateCertificateIssueRequest, opts ...grpc.CallOption) (*CertificateIssue, error)
}

type certificateIssueServiceClient struct {
	cc *grpc.ClientConn
}

func NewCertificateIssueServiceClient(cc *grpc.ClientConn) CertificateIssueServiceClient {
	return &certificateIssueServiceClient{cc}
}

func (c *certificateIssueServiceClient) Create(ctx context.Context, in *CreateCertificateIssueRequest, opts ...grpc.CallOption) (*CertificateIssue, error) {
	out := new(CertificateIssue)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateIssueService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateIssueServiceClient) Delete(ctx context.Context, in *DeleteCertificateIssueRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateIssueService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateIssueServiceClient) Get(ctx context.Context, in *GetCertificateIssueRequest, opts ...grpc.CallOption) (*CertificateIssue, error) {
	out := new(CertificateIssue)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateIssueService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateIssueServiceClient) List(ctx context.Context, in *ListCertificateIssuesRequest, opts ...grpc.CallOption) (*ListCertificateIssuesResponse, error) {
	out := new(ListCertificateIssuesResponse)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateIssueService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateIssueServiceClient) Update(ctx context.Context, in *UpdateCertificateIssueRequest, opts ...grpc.CallOption) (*CertificateIssue, error) {
	out := new(CertificateIssue)
	err := c.cc.Invoke(ctx, "/powerssl.apiserver.v1.CertificateIssueService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CertificateIssueService service

type CertificateIssueServiceServer interface {
	// Creates a certificate, and returns the new CertificateIssue.
	Create(context.Context, *CreateCertificateIssueRequest) (*CertificateIssue, error)
	// Deletes a certificate. Returns NOT_FOUND if the certificate does not exist.
	Delete(context.Context, *DeleteCertificateIssueRequest) (*types.Empty, error)
	// Gets a certificate. Returns NOT_FOUND if the certificate does not exist.
	Get(context.Context, *GetCertificateIssueRequest) (*CertificateIssue, error)
	// Lists certificates. The order is unspecified but deterministic. Newly created
	// certificates will not necessarily be added to the end of this list.
	List(context.Context, *ListCertificateIssuesRequest) (*ListCertificateIssuesResponse, error)
	// Updates a certificate. Returns INVALID_ARGUMENT if the name of the certificate
	// is non-empty and does equal the previous name.
	Update(context.Context, *UpdateCertificateIssueRequest) (*CertificateIssue, error)
}

func RegisterCertificateIssueServiceServer(s *grpc.Server, srv CertificateIssueServiceServer) {
	s.RegisterService(&_CertificateIssueService_serviceDesc, srv)
}

func _CertificateIssueService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCertificateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssueServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateIssueService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssueServiceServer).Create(ctx, req.(*CreateCertificateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateIssueService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCertificateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssueServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateIssueService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssueServiceServer).Delete(ctx, req.(*DeleteCertificateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateIssueService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssueServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateIssueService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssueServiceServer).Get(ctx, req.(*GetCertificateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateIssueService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificateIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssueServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateIssueService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssueServiceServer).List(ctx, req.(*ListCertificateIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateIssueService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCertificateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssueServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powerssl.apiserver.v1.CertificateIssueService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssueServiceServer).Update(ctx, req.(*UpdateCertificateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertificateIssueService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "powerssl.apiserver.v1.CertificateIssueService",
	HandlerType: (*CertificateIssueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CertificateIssueService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CertificateIssueService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CertificateIssueService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CertificateIssueService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CertificateIssueService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiserver/api/v1/certificate_issue.proto",
}

func init() {
	proto.RegisterFile("apiserver/api/v1/certificate_issue.proto", fileDescriptor_certificate_issue_bb99f45ab1c55a6f)
}

var fileDescriptor_certificate_issue_bb99f45ab1c55a6f = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xcf, 0x4f, 0xe3, 0x46,
	0x14, 0xc7, 0xe5, 0xfc, 0x22, 0x79, 0x01, 0x11, 0x46, 0x2d, 0x75, 0x0d, 0x51, 0x53, 0x17, 0xd1,
	0x34, 0x95, 0xec, 0x06, 0x38, 0xb4, 0xa0, 0x1e, 0x5a, 0x8a, 0x50, 0x55, 0x54, 0x55, 0x86, 0xee,
	0x61, 0x2f, 0x91, 0x49, 0x1e, 0xd9, 0x51, 0x1c, 0xdb, 0xeb, 0x99, 0x84, 0x0d, 0x2b, 0x2e, 0x9c,
	0x76, 0x0f, 0x9c, 0xf6, 0xb6, 0xd2, 0x6a, 0xcf, 0xfb, 0xf7, 0xec, 0xbf, 0xb0, 0x7f, 0xc8, 0x6a,
	0x66, 0x4c, 0x88, 0x1c, 0x1c, 0x92, 0xc3, 0x9e, 0xe2, 0x79, 0x33, 0xef, 0xf9, 0x93, 0xef, 0xfb,
	0xbe, 0x91, 0xa1, 0xee, 0x86, 0x94, 0x61, 0x34, 0xc4, 0xc8, 0x76, 0x43, 0x6a, 0x0f, 0x9b, 0x76,
	0x1b, 0x23, 0x4e, 0x2f, 0x68, 0xdb, 0xe5, 0xd8, 0xa2, 0x8c, 0x0d, 0xd0, 0x0a, 0xa3, 0x80, 0x07,
	0xe4, 0xeb, 0x30, 0xb8, 0xc4, 0x88, 0x31, 0xcf, 0x1a, 0xa7, 0x58, 0xc3, 0xa6, 0xb1, 0xd9, 0x0d,
	0x82, 0xae, 0x87, 0x32, 0xdb, 0xf5, 0xfd, 0x80, 0xbb, 0x9c, 0x06, 0x3e, 0x53, 0x49, 0xc6, 0x46,
	0xbc, 0x2b, 0x57, 0xe7, 0x83, 0x0b, 0x1b, 0xfb, 0x21, 0x1f, 0xc5, 0x9b, 0xdf, 0x25, 0x37, 0x39,
	0xed, 0x23, 0xe3, 0x6e, 0x3f, 0x54, 0x07, 0xcc, 0x0f, 0x39, 0xa8, 0x1c, 0xde, 0xe3, 0xfc, 0x2d,
	0x68, 0x08, 0x81, 0x9c, 0xef, 0xf6, 0x51, 0xd7, 0x6a, 0x5a, 0xbd, 0xe4, 0xc8, 0x67, 0x72, 0x00,
	0xe5, 0x76, 0x84, 0x82, 0x58, 0x94, 0xd0, 0x33, 0x35, 0xad, 0x5e, 0xde, 0x31, 0x2c, 0x55, 0xdf,
	0xba, 0xab, 0x6f, 0x9d, 0xdd, 0xd5, 0x77, 0x40, 0x1d, 0x17, 0x01, 0x91, 0x3c, 0x08, 0x3b, 0xe3,
	0xe4, 0xec, 0xe3, 0xc9, 0xea, 0xb8, 0x4c, 0xfe, 0x1e, 0x96, 0x3b, 0x94, 0x85, 0x9e, 0x3b, 0x6a,
	0x49, 0xaa, 0x9c, 0xa4, 0x2a, 0xc7, 0xb1, 0x7f, 0x05, 0xdc, 0x57, 0x90, 0xe7, 0x94, 0x7b, 0xa8,
	0xe7, 0xe5, 0x9e, 0x5a, 0x90, 0x1a, 0x94, 0x3b, 0xc8, 0xda, 0x11, 0x0d, 0x85, 0x5e, 0x7a, 0x21,
	0xce, 0xbb, 0x0f, 0x91, 0x7f, 0xa0, 0xe0, 0xb9, 0xe7, 0xe8, 0x31, 0x7d, 0xa9, 0x96, 0xad, 0x97,
	0x77, 0x76, 0xad, 0x07, 0x3b, 0x60, 0x25, 0x15, 0xb2, 0x4e, 0x64, 0xd6, 0x91, 0xcf, 0xa3, 0x91,
	0x13, 0x97, 0x20, 0x06, 0x14, 0x3b, 0x3e, 0x13, 0x88, 0x4c, 0x2f, 0xd6, 0xb2, 0xf5, 0x92, 0x33,
	0x5e, 0x93, 0x1f, 0x60, 0xa5, 0x87, 0xa3, 0x96, 0xeb, 0x75, 0x83, 0x88, 0xf2, 0x67, 0x7d, 0xbd,
	0x24, 0x61, 0x96, 0x7b, 0x38, 0xfa, 0xe3, 0x2e, 0x46, 0xbe, 0x85, 0xa2, 0x38, 0xc4, 0xe8, 0x15,
	0xea, 0x50, 0xd3, 0xea, 0x79, 0x67, 0xa9, 0x87, 0xa3, 0x53, 0x7a, 0x85, 0xe4, 0x27, 0xa8, 0x74,
	0x68, 0x17, 0x19, 0x9f, 0x28, 0x51, 0x96, 0x25, 0x56, 0x55, 0xfc, 0xbe, 0x4a, 0x15, 0xc0, 0x1d,
	0xf0, 0xa0, 0x15, 0xa1, 0x8f, 0x97, 0xfa, 0x72, 0x4d, 0xab, 0x17, 0x9d, 0x92, 0x88, 0x38, 0x22,
	0x60, 0xfc, 0x06, 0xe5, 0x09, 0x78, 0x52, 0x81, 0x6c, 0x0f, 0x47, 0x71, 0xa7, 0xc5, 0xa3, 0xd0,
	0x72, 0xe8, 0x7a, 0x03, 0xd5, 0xe2, 0x92, 0xa3, 0x16, 0xfb, 0x99, 0x5f, 0x35, 0xf3, 0x56, 0x83,
	0xea, 0xa1, 0x6c, 0x6a, 0x52, 0x0f, 0x07, 0x9f, 0x0f, 0x90, 0x71, 0xb2, 0x0e, 0x85, 0xd0, 0x8d,
	0xd0, 0xe7, 0x71, 0xc1, 0x78, 0x45, 0xce, 0x60, 0x6d, 0xca, 0xf3, 0xb1, 0x85, 0x7e, 0x9c, 0x53,
	0x72, 0xa7, 0xd2, 0x4e, 0x44, 0xcc, 0x5d, 0xa8, 0xfe, 0x85, 0x1e, 0xa6, 0xe3, 0x3c, 0xe0, 0x63,
	0xf3, 0x17, 0x30, 0x8e, 0x91, 0x2f, 0x92, 0x11, 0xc1, 0xe6, 0x09, 0x65, 0x53, 0x29, 0xec, 0xb1,
	0x3f, 0xbd, 0x01, 0xa5, 0xd0, 0xed, 0xa2, 0xea, 0x67, 0x46, 0xf6, 0xb3, 0x28, 0x02, 0xb2, 0xa1,
	0x55, 0x00, 0xb9, 0xc9, 0x83, 0x1e, 0xfa, 0x72, 0x20, 0x4a, 0x8e, 0x3c, 0x7e, 0x26, 0x02, 0xe6,
	0x7b, 0x0d, 0xaa, 0x29, 0x2f, 0x65, 0x61, 0xe0, 0x33, 0x24, 0x4f, 0x80, 0x4c, 0x49, 0xca, 0x74,
	0x4d, 0xda, 0x78, 0x6e, 0x4d, 0xd7, 0x92, 0x9a, 0x32, 0xb2, 0x0d, 0xab, 0x3e, 0xbe, 0xe0, 0xad,
	0x09, 0x3a, 0x65, 0x84, 0x15, 0x11, 0xfe, 0x6f, 0x4c, 0xf8, 0x5a, 0x83, 0xea, 0xff, 0x72, 0x48,
	0x17, 0xd0, 0xf2, 0xcb, 0x18, 0x61, 0xe7, 0x55, 0x01, 0xbe, 0x49, 0x1e, 0x3b, 0xc5, 0x68, 0x48,
	0xdb, 0x48, 0xde, 0x6a, 0x50, 0x50, 0xa6, 0x25, 0x7b, 0x69, 0x6f, 0x98, 0xe5, 0x69, 0x63, 0x5e,
	0x2e, 0xb3, 0x79, 0xf3, 0xf1, 0xd3, 0x9b, 0xcc, 0xcf, 0xa6, 0x29, 0xae, 0xf8, 0x97, 0xca, 0x04,
	0xbf, 0x4f, 0xb0, 0x32, 0xbb, 0x71, 0x6d, 0xab, 0x3e, 0xed, 0xe7, 0xe5, 0x2f, 0xb9, 0xd1, 0xa0,
	0xa0, 0x2c, 0x9c, 0x0a, 0x37, 0xd3, 0xe1, 0xc6, 0xfa, 0xd4, 0x1d, 0x7a, 0x24, 0x6e, 0x7f, 0xb3,
	0x21, 0x59, 0xb6, 0x1a, 0x8a, 0x45, 0x48, 0x9f, 0x20, 0x89, 0x41, 0xec, 0xc6, 0x35, 0xb9, 0xd5,
	0x20, 0x7b, 0x8c, 0x9c, 0x34, 0x53, 0x08, 0xd2, 0xc7, 0x65, 0x7e, 0x6d, 0x62, 0x1e, 0x32, 0x0f,
	0xcf, 0x3b, 0x0d, 0x72, 0xc2, 0xfb, 0x24, 0xed, 0x36, 0x9e, 0x35, 0x8d, 0xc6, 0xde, 0x62, 0x49,
	0x6a, 0x9a, 0x12, 0x7c, 0x33, 0x7b, 0x27, 0x1d, 0xa5, 0x9c, 0x9f, 0xda, 0xb4, 0x99, 0x83, 0xb1,
	0xb0, 0xa3, 0x8c, 0x39, 0x54, 0x8b, 0x1d, 0xf5, 0xe7, 0xf6, 0xd3, 0xad, 0x71, 0x71, 0x1a, 0xd8,
	0x61, 0xaf, 0x6b, 0x27, 0x3f, 0x3f, 0x0e, 0xdc, 0x90, 0x9e, 0x17, 0xa4, 0x61, 0x76, 0x3f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xdd, 0x48, 0x4a, 0x7d, 0x9d, 0x08, 0x00, 0x00,
}
