log:
  env: development
server:
  apiAddr: localhost:8082
  addr: localhost:8443
  authURI: https://localhost:8843
  certFile: local/certs/localhost.pem
  grpcWebURI: https://localhost:8883
  insecure: false
  keyFile: local/certs/localhost-key.pem
telemetry:
  meter:
    addr: localhost:9090
    exporter: prometheus
  tracer:
    exporter: jaeger
