openapi: 3.0.0
info:
  title: powerssl/apiserver/v1/acme_server.proto
  version: v1
tags:
  - name: ACMEServerService
paths:
  /v1/acmeServers:
    get:
      operationId: ACMEServerService_List
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ListACMEServersResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageToken
          in: query
          required: false
          schema:
            type: string
      tags:
        - ACMEServerService
      security:
        - bearerAuth: []
    post:
      operationId: ACMEServerService_Create
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ACMEServer'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1CreateACMEServerRequest'
        required: true
      tags:
        - ACMEServerService
      security:
        - bearerAuth: []
  /v1/{name}:
    get:
      operationId: ACMEServerService_Get
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ACMEServer'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          example: acmeServers/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+$
      tags:
        - ACMEServerService
      security:
        - bearerAuth: []
    delete:
      operationId: ACMEServerService_Delete
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                properties: {}
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          example: acmeServers/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+$
      tags:
        - ACMEServerService
      security:
        - bearerAuth: []
    put:
      operationId: ACMEServerService_Update
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ACMEServer'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          example: acmeServers/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+$
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1UpdateACMEServerRequest'
        required: true
      tags:
        - ACMEServerService
      security:
        - bearerAuth: []
components:
  schemas:
    protobufAny:
      type: object
      properties:
        typeUrl:
          type: string
        value:
          type: string
          format: byte
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
    v1ACMEServer:
      type: object
      properties:
        name:
          type: string
        createTime:
          type: string
          format: date-time
        updateTime:
          type: string
          format: date-time
        displayName:
          type: string
        directoryUrl:
          type: string
        integrationName:
          type: string
    v1CreateACMEServerRequest:
      type: object
      properties:
        acmeServer:
          $ref: '#/components/schemas/v1ACMEServer'
    v1ListACMEServersResponse:
      type: object
      properties:
        acmeServers:
          type: array
          items:
            $ref: '#/components/schemas/v1ACMEServer'
        nextPageToken:
          type: string
    v1UpdateACMEServerRequest:
      type: object
      properties:
        name:
          type: string
        updateMask:
          type: string
        acmeServer:
          $ref: '#/components/schemas/v1ACMEServer'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
