openapi: 3.0.0
info:
  title: powerssl/apiserver/v1/acme_account.proto
  version: v1
tags:
  - name: ACMEAccountService
paths:
  /v1/{name}:
    get:
      operationId: ACMEAccountService_Get
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ACMEAccount'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          example: acmeServers/*/acmeAccounts/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+\/acmeAccounts\/\w+$
      tags:
        - ACMEAccountService
      security:
        - bearerAuth: []
    delete:
      operationId: ACMEAccountService_Delete
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                properties: {}
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          example: acmeServers/*/acmeAccounts/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+\/acmeAccounts\/\w+$
      tags:
        - ACMEAccountService
      security:
        - bearerAuth: []
    put:
      operationId: ACMEAccountService_Update
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ACMEAccount'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: name
          in: path
          required: true
          example: acmeServers/*/acmeAccounts/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+\/acmeAccounts\/\w+$
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                updateMask:
                  type: string
                acmeAccount:
                  $ref: '#/components/schemas/v1ACMEAccount'
        required: true
      tags:
        - ACMEAccountService
      security:
        - bearerAuth: []
  /v1/{parent}/acmeAccounts:
    get:
      operationId: ACMEAccountService_List
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ListACMEAccountsResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: parent
          in: path
          required: true
          example: acmeServers/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+$
        - name: query
          in: query
          required: false
          schema:
            type: string
        - name: pageToken
          in: query
          required: false
          schema:
            type: string
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
      tags:
        - ACMEAccountService
      security:
        - bearerAuth: []
    post:
      operationId: ACMEAccountService_Create
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ACMEAccount'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      parameters:
        - name: parent
          in: path
          required: true
          example: acmeServers/*
          schema:
            type: string
            pattern: ^acmeServers\/\w+$
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                acmeAccount:
                  $ref: '#/components/schemas/v1ACMEAccount'
        required: true
      tags:
        - ACMEAccountService
      security:
        - bearerAuth: []
components:
  schemas:
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties: {}
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
    v1ACMEAccount:
      type: object
      properties:
        name:
          type: string
        createTime:
          type: string
          format: date-time
        updateTime:
          type: string
          format: date-time
        displayName:
          type: string
        title:
          type: string
        description:
          type: string
        labels:
          type: object
          additionalProperties:
            type: string
        termsOfServiceAgreed:
          type: boolean
        contacts:
          type: array
          items:
            type: string
        accountUrl:
          type: string
    v1ListACMEAccountsResponse:
      type: object
      properties:
        acmeAccounts:
          type: array
          items:
            $ref: '#/components/schemas/v1ACMEAccount'
        nextPageToken:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
